export type VehicleClass =
  | 'HYPERCAR'
  | 'SUPERCAR'
  | 'JDM_DRIFT'
  | 'AMERICAN_MUSCLE'
  | 'GERMAN_EXECUTIVE'
  | 'TRACK_SPECIAL'
  | 'OFFROAD_4X4'
  | 'ELECTRIC_HYPER_EV'
  | 'COMMERCIAL_HAULER'
  | 'URBAN_TRANSIT'
  | 'VINTAGE_CLASSIC';

export type PerformanceTier = 'D' | 'C' | 'B' | 'A' | 'S' | 'S_PLUS' | 'X';

export type DrivetrainLayout = 'FWD' | 'RWD' | 'AWD' | '4WD';

export type EngineConfiguration =
  | 'INLINE_3_TURBO'
  | 'INLINE_4_NA'
  | 'INLINE_4_TURBO'
  | 'INLINE_6_TWIN_TURBO'
  | 'TWIN_ROTOR_WANKEL'
  | 'V6_TWIN_TURBO'
  | 'V8_CROSSPLANE_NA'
  | 'V8_FLATPLANE_NA'
  | 'V8_SUPERCHARGED'
  | 'V8_TWIN_TURBO'
  | 'V10_NA'
  | 'V12_NA'
  | 'V12_TWIN_TURBO'
  | 'W16_QUAD_TURBO'
  | 'DUAL_MOTOR_EV'
  | 'TRI_MOTOR_EV'
  | 'QUAD_MOTOR_EV'
  | 'HEAVY_INLINE_6_TURBODIESEL'
  | 'V8_TURBODIESEL';

export interface VehicleCatalogEntry {
  id: string;
  name: string;
  make: string;
  model: string;
  year: number;
  vehicleClass: VehicleClass;
  tier: PerformanceTier;
  priceCredits: number;
  unlockLevel: number;
  drivetrain: DrivetrainLayout;
  engineConfig: EngineConfiguration;
  displacementLiters: number;
  peakHorsepower: number;
  peakHorsepowerRpm: number;
  peakTorqueNm: number;
  peakTorqueRpm: number;
  redlineRpm: number;
  idleRpm: number;
  weightKg: number;
  weightDistributionFront: number; // e.g. 0.52 for 52/48 front/rear
  dragCoefficient: number;
  frontalAreaSqMeters: number;
  downforceKgAt200Kmh: number;
  topSpeedKmh: number;
  zeroToHundredSec: number;
  quarterMileSec: number;
  fuelCapacityLiters: number;
  fuelType: 'GASOLINE_98' | 'GASOLINE_E85' | 'RACING_110_OCTANE' | 'DIESEL' | 'ELECTRIC_KWH';
  electricBatteryKwh?: number;
  brakeRotorFrontMm: number;
  brakeRotorRearMm: number;
  brakePistonsFront: number;
  brakePistonsRear: number;
  tireWidthFrontMm: number;
  tireWidthRearMm: number;
  wheelDiameterInches: number;
  factoryPaintColors: { name: string; hex: number }[];
  description: string;
  loreBiography: string;
}

export const VEHICLE_CATALOG_DATA: VehicleCatalogEntry[] = [
  // =========================================================================
  // 1. HYPERCARS & SUPERCAR PINNACLES (1-7)
  // =========================================================================
  {
    id: 'veh_koenigsegg_jesko',
    name: 'AeroStrike 300 Ghost',
    make: 'AeroStrike',
    model: 'Ghost 300 V8',
    year: 2024,
    vehicleClass: 'HYPERCAR',
    tier: 'X',
    priceCredits: 3400000,
    unlockLevel: 50,
    drivetrain: 'RWD',
    engineConfig: 'V8_TWIN_TURBO',
    displacementLiters: 5.0,
    peakHorsepower: 1600,
    peakHorsepowerRpm: 7800,
    peakTorqueNm: 1500,
    peakTorqueRpm: 5100,
    redlineRpm: 8500,
    idleRpm: 950,
    weightKg: 1420,
    weightDistributionFront: 0.44,
    dragCoefficient: 0.28,
    frontalAreaSqMeters: 1.88,
    downforceKgAt200Kmh: 800,
    topSpeedKmh: 480,
    zeroToHundredSec: 2.5,
    quarterMileSec: 8.9,
    fuelCapacityLiters: 72,
    fuelType: 'GASOLINE_E85',
    brakeRotorFrontMm: 410,
    brakeRotorRearMm: 395,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 265,
    tireWidthRearMm: 345,
    wheelDiameterInches: 21,
    factoryPaintColors: [
      { name: 'Ghost Pearl White', hex: 0xf4f6f7 },
      { name: 'Imperial Carbon Silver', hex: 0x566573 },
      { name: 'Apex Sunburst Gold', hex: 0xf39c12 },
    ],
    description: 'Uncompromising Swedish engineering with 1600 horsepower, a 9-speed multi-clutch Light Speed transmission, and active active aero.',
    loreBiography: 'Forged in a former fighter jet hangar, the Ghost 300 represents the apex of aerodynamic drag reduction and internal combustion power density.',
  },
  {
    id: 'veh_bugatti_chiron',
    name: 'Monarch W16 Quad-Turbo Grand',
    make: 'Monarch',
    model: 'Grand Sport W16',
    year: 2023,
    vehicleClass: 'HYPERCAR',
    tier: 'X',
    priceCredits: 3800000,
    unlockLevel: 55,
    drivetrain: 'AWD',
    engineConfig: 'W16_QUAD_TURBO',
    displacementLiters: 8.0,
    peakHorsepower: 1500,
    peakHorsepowerRpm: 6700,
    peakTorqueNm: 1600,
    peakTorqueRpm: 2000,
    redlineRpm: 7100,
    idleRpm: 750,
    weightKg: 1995,
    weightDistributionFront: 0.45,
    dragCoefficient: 0.35,
    frontalAreaSqMeters: 2.05,
    downforceKgAt200Kmh: 350,
    topSpeedKmh: 420,
    zeroToHundredSec: 2.4,
    quarterMileSec: 9.3,
    fuelCapacityLiters: 100,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 420,
    brakeRotorRearMm: 400,
    brakePistonsFront: 8,
    brakePistonsRear: 6,
    tireWidthFrontMm: 285,
    tireWidthRearMm: 355,
    wheelDiameterInches: 21,
    factoryPaintColors: [
      { name: 'French Racing Dual Blue', hex: 0x1b4f72 },
      { name: 'Nocturne Metallic Obsidian', hex: 0x111111 },
      { name: 'Italian Red & Exposed Carbon', hex: 0x922b21 },
    ],
    description: 'An iconic 8.0-liter quad-turbocharged W16 luxury land rocket with unrelenting all-wheel-drive thrust.',
    loreBiography: 'Crafted for continent-crossing speed records in sheer bespoke luxury. Holds the distinction of consuming 60,000 liters of air every minute at full throttle.',
  },
  {
    id: 'veh_porsche_gt3_rs',
    name: 'Stuttgart 992 Weissach RS',
    make: 'Stuttgart',
    model: '992 GT3 RS',
    year: 2024,
    vehicleClass: 'SUPERCAR',
    tier: 'S_PLUS',
    priceCredits: 380000,
    unlockLevel: 38,
    drivetrain: 'RWD',
    engineConfig: 'V8_FLATPLANE_NA', // Flat-6 high-rev
    displacementLiters: 4.0,
    peakHorsepower: 525,
    peakHorsepowerRpm: 8500,
    peakTorqueNm: 465,
    peakTorqueRpm: 6300,
    redlineRpm: 9000,
    idleRpm: 900,
    weightKg: 1450,
    weightDistributionFront: 0.39,
    dragCoefficient: 0.39,
    frontalAreaSqMeters: 2.02,
    downforceKgAt200Kmh: 860,
    topSpeedKmh: 296,
    zeroToHundredSec: 3.2,
    quarterMileSec: 10.9,
    fuelCapacityLiters: 64,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 410,
    brakeRotorRearMm: 390,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 275,
    tireWidthRearMm: 335,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Lizard Green Weissach', hex: 0x27ae60 },
      { name: 'Shark Blue Track Edition', hex: 0x2980b9 },
      { name: 'Arctic Grey Carbon', hex: 0x7f8c8d },
    ],
    description: 'Naturally aspirated 9,000 RPM precision weapon with swan-neck active DRS wing and Formula 1-level downforce.',
    loreBiography: 'Developed on the Nürburgring Nordschleife with zero compromises. Capable of pulling over 2.0G of lateral acceleration in high-speed bends.',
  },
  {
    id: 'veh_ferrari_sf90',
    name: 'Maranello Stradale V8 Hybrid',
    make: 'Maranello',
    model: 'Stradale 1000 Hybrid',
    year: 2023,
    vehicleClass: 'HYPERCAR',
    tier: 'X',
    priceCredits: 620000,
    unlockLevel: 45,
    drivetrain: 'AWD',
    engineConfig: 'V8_TWIN_TURBO',
    displacementLiters: 4.0,
    peakHorsepower: 986,
    peakHorsepowerRpm: 7500,
    peakTorqueNm: 800,
    peakTorqueRpm: 6000,
    redlineRpm: 8000,
    idleRpm: 850,
    weightKg: 1570,
    weightDistributionFront: 0.45,
    dragCoefficient: 0.32,
    frontalAreaSqMeters: 1.95,
    downforceKgAt200Kmh: 390,
    topSpeedKmh: 340,
    zeroToHundredSec: 2.3,
    quarterMileSec: 9.6,
    fuelCapacityLiters: 68,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 398,
    brakeRotorRearMm: 360,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 255,
    tireWidthRearMm: 315,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Rosso Corsa Racing Red', hex: 0xc0392b },
      { name: 'Giallo Modena Fly Yellow', hex: 0xf1c40f },
      { name: 'Nero Daytona Gloss Black', hex: 0x0e1111 },
    ],
    description: 'Twin-turbocharged 4.0L V8 paired with three electric motors producing a ferocious 986 combined horsepower through AWD.',
    loreBiography: 'Named to celebrate racing heritage, bridging the gap between Scuderia Formula 1 kinetic energy recovery and road-legal hypercars.',
  },
  {
    id: 'veh_mclaren_720s',
    name: 'Woking Velocity 720 Twin-Turbo',
    make: 'Woking',
    model: 'Velocity 720S',
    year: 2022,
    vehicleClass: 'SUPERCAR',
    tier: 'S_PLUS',
    priceCredits: 310000,
    unlockLevel: 35,
    drivetrain: 'RWD',
    engineConfig: 'V8_TWIN_TURBO',
    displacementLiters: 4.0,
    peakHorsepower: 710,
    peakHorsepowerRpm: 7500,
    peakTorqueNm: 770,
    peakTorqueRpm: 5500,
    redlineRpm: 8500,
    idleRpm: 900,
    weightKg: 1283,
    weightDistributionFront: 0.42,
    dragCoefficient: 0.32,
    frontalAreaSqMeters: 1.92,
    downforceKgAt200Kmh: 320,
    topSpeedKmh: 341,
    zeroToHundredSec: 2.8,
    quarterMileSec: 10.1,
    fuelCapacityLiters: 72,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 390,
    brakeRotorRearMm: 380,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 245,
    tireWidthRearMm: 305,
    wheelDiameterInches: 19,
    factoryPaintColors: [
      { name: 'Papaya Racing Orange', hex: 0xe67e22 },
      { name: 'Volcano Metallic Blue', hex: 0x2471a3 },
      { name: 'Silica Frost White', hex: 0xecf0f1 },
    ],
    description: 'Carbon fiber Monocage II tub chassis with hydraulic Proactive Chassis Control and dihedral doors.',
    loreBiography: 'An aerodynamic marvel engineered in Surrey wind tunnels, boasting one of the best power-to-weight ratios in the modern supercar era.',
  },
  {
    id: 'veh_lamborghini_huracan_sto',
    name: 'SantAgata Trofeo STO V10',
    make: 'SantAgata',
    model: 'Huracan Super Trofeo Omologata',
    year: 2023,
    vehicleClass: 'SUPERCAR',
    tier: 'S_PLUS',
    priceCredits: 350000,
    unlockLevel: 36,
    drivetrain: 'RWD',
    engineConfig: 'V10_NA',
    displacementLiters: 5.2,
    peakHorsepower: 631,
    peakHorsepowerRpm: 8000,
    peakTorqueNm: 565,
    peakTorqueRpm: 6500,
    redlineRpm: 8500,
    idleRpm: 950,
    weightKg: 1339,
    weightDistributionFront: 0.41,
    dragCoefficient: 0.36,
    frontalAreaSqMeters: 2.01,
    downforceKgAt200Kmh: 450,
    topSpeedKmh: 310,
    zeroToHundredSec: 3.0,
    quarterMileSec: 10.5,
    fuelCapacityLiters: 80,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 390,
    brakeRotorRearMm: 360,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 245,
    tireWidthRearMm: 305,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Blu Laufey Matte & Arancio', hex: 0x2980b9 },
      { name: 'Verde Mantis Pearl Green', hex: 0x2ecc71 },
      { name: 'Grigio Titans Matte Charcoal', hex: 0x34495e },
    ],
    description: 'Screaming 5.2L naturally aspirated V10 with rear-wheel drive, roof air scoop, and single-piece carbon fiber Cofango clamshell.',
    loreBiography: 'Born directly from Lamborghini Super Trofeo and GT3 racing programs, delivering an unfiltered operatic exhaust note.',
  },
  {
    id: 'veh_aston_valkyrie',
    name: 'Gaydon Nebula AMR V12',
    make: 'Gaydon',
    model: 'Nebula Hypercar V12',
    year: 2024,
    vehicleClass: 'HYPERCAR',
    tier: 'X',
    priceCredits: 3200000,
    unlockLevel: 48,
    drivetrain: 'RWD',
    engineConfig: 'V12_NA',
    displacementLiters: 6.5,
    peakHorsepower: 1160,
    peakHorsepowerRpm: 10500,
    peakTorqueNm: 740,
    peakTorqueRpm: 7000,
    redlineRpm: 11100,
    idleRpm: 1100,
    weightKg: 1030,
    weightDistributionFront: 0.43,
    dragCoefficient: 0.34,
    frontalAreaSqMeters: 1.75,
    downforceKgAt200Kmh: 1100,
    topSpeedKmh: 402,
    zeroToHundredSec: 2.5,
    quarterMileSec: 9.1,
    fuelCapacityLiters: 60,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 420,
    brakeRotorRearMm: 385,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 265,
    tireWidthRearMm: 325,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Stirling Green AMR', hex: 0x145a32 },
      { name: 'Hyper Red Metallic', hex: 0x922b21 },
      { name: 'Scintilla Silver Metallic', hex: 0xbdc3c7 },
    ],
    description: 'Cosworth-developed 6.5L naturally aspirated V12 that screams to an astonishing 11,100 RPM with massive Venturi underbody tunnels.',
    loreBiography: 'Designed by legendary Formula 1 aerodynamicist Adrian Newey. Generates more downforce than its entire curb weight at terminal velocity.',
  },

  // =========================================================================
  // 2. JDM & DRIFT LEGENDS (8-15)
  // =========================================================================
  {
    id: 'veh_nissan_skyline_r34',
    name: 'Yokohama V-Spec II Twin Turbo',
    make: 'Yokohama',
    model: 'Skyline GT-R R34 V-Spec',
    year: 2002,
    vehicleClass: 'JDM_DRIFT',
    tier: 'A',
    priceCredits: 145000,
    unlockLevel: 18,
    drivetrain: 'AWD',
    engineConfig: 'INLINE_6_TWIN_TURBO',
    displacementLiters: 2.6,
    peakHorsepower: 327,
    peakHorsepowerRpm: 6800,
    peakTorqueNm: 392,
    peakTorqueRpm: 4400,
    redlineRpm: 8000,
    idleRpm: 850,
    weightKg: 1560,
    weightDistributionFront: 0.54,
    dragCoefficient: 0.34,
    frontalAreaSqMeters: 2.1,
    downforceKgAt200Kmh: 80,
    topSpeedKmh: 265,
    zeroToHundredSec: 4.8,
    quarterMileSec: 12.8,
    fuelCapacityLiters: 65,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 324,
    brakeRotorRearMm: 300,
    brakePistonsFront: 4,
    brakePistonsRear: 2,
    tireWidthFrontMm: 245,
    tireWidthRearMm: 245,
    wheelDiameterInches: 18,
    factoryPaintColors: [
      { name: 'Bayside Blue Pearl', hex: 0x1b4f72 },
      { name: 'Midnight Purple III Chameleon', hex: 0x4a235a },
      { name: 'Millennium Jade Metallic', hex: 0x7d6608 },
    ],
    description: 'The legendary RB26DETT twin-turbo inline-6 with ATTESA E-TS Pro all-wheel-drive and active rear LSD.',
    loreBiography: 'Nicknamed "Godzilla" across global motorsport circuits. The R34 dominated touring car championships and street racing lore across the world.',
  },
  {
    id: 'veh_toyota_supra_mk4',
    name: 'Aichi 2JZ Twin-Turbo Turbocharged',
    make: 'Aichi',
    model: 'Supra RZ Twin Turbo MK4',
    year: 1998,
    vehicleClass: 'JDM_DRIFT',
    tier: 'A',
    priceCredits: 135000,
    unlockLevel: 16,
    drivetrain: 'RWD',
    engineConfig: 'INLINE_6_TWIN_TURBO',
    displacementLiters: 3.0,
    peakHorsepower: 320,
    peakHorsepowerRpm: 5600,
    peakTorqueNm: 441,
    peakTorqueRpm: 4000,
    redlineRpm: 7200,
    idleRpm: 750,
    weightKg: 1510,
    weightDistributionFront: 0.53,
    dragCoefficient: 0.31,
    frontalAreaSqMeters: 2.05,
    downforceKgAt200Kmh: 60,
    topSpeedKmh: 270,
    zeroToHundredSec: 4.9,
    quarterMileSec: 13.1,
    fuelCapacityLiters: 70,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 323,
    brakeRotorRearMm: 324,
    brakePistonsFront: 4,
    brakePistonsRear: 2,
    tireWidthFrontMm: 235,
    tireWidthRearMm: 255,
    wheelDiameterInches: 17,
    factoryPaintColors: [
      { name: 'Super White II', hex: 0xfafafa },
      { name: 'Renaissance Red', hex: 0xc0392b },
      { name: 'Quicksilver Metallic', hex: 0x95a5a6 },
    ],
    description: 'Bulletproof cast-iron block 2JZ-GTE sequential twin-turbo inline-6 capable of easily exceeding 1,000 HP with aftermarket boost.',
    loreBiography: 'An immortal legend of highway roll racing and quarter-mile drag strips, celebrated worldwide for its virtually indestructible engine architecture.',
  },
  {
    id: 'veh_mazda_rx7_fd',
    name: 'Hiroshima Efini Twin-Rotary Turbo',
    make: 'Hiroshima',
    model: 'RX-7 Spirit R Type A',
    year: 2002,
    vehicleClass: 'JDM_DRIFT',
    tier: 'A',
    priceCredits: 120000,
    unlockLevel: 15,
    drivetrain: 'RWD',
    engineConfig: 'TWIN_ROTOR_WANKEL',
    displacementLiters: 1.3,
    peakHorsepower: 276,
    peakHorsepowerRpm: 6500,
    peakTorqueNm: 314,
    peakTorqueRpm: 5000,
    redlineRpm: 8200,
    idleRpm: 800,
    weightKg: 1270,
    weightDistributionFront: 0.50,
    dragCoefficient: 0.29,
    frontalAreaSqMeters: 1.88,
    downforceKgAt200Kmh: 45,
    topSpeedKmh: 256,
    zeroToHundredSec: 5.1,
    quarterMileSec: 13.4,
    fuelCapacityLiters: 76,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 314,
    brakeRotorRearMm: 314,
    brakePistonsFront: 4,
    brakePistonsRear: 1,
    tireWidthFrontMm: 235,
    tireWidthRearMm: 255,
    wheelDiameterInches: 17,
    factoryPaintColors: [
      { name: 'Titanium Gray Metallic', hex: 0x566573 },
      { name: 'Innocent Blue Mica', hex: 0x2471a3 },
      { name: 'Pure White Gloss', hex: 0xfdfefe },
    ],
    description: '13B-REW sequential twin-turbocharged rotary engine with 50:50 front/rear balance and featherweight handling chassis.',
    loreBiography: 'Renowned for its low center of gravity, screaming rotary tachometer, and timeless organic styling that remains an artistic benchmark.',
  },
  {
    id: 'veh_nissan_silvia_s15',
    name: 'Kanagawa Spec-R Aero Drift',
    make: 'Kanagawa',
    model: 'Silvia S15 Spec-R Aero',
    year: 2001,
    vehicleClass: 'JDM_DRIFT',
    tier: 'B',
    priceCredits: 75000,
    unlockLevel: 10,
    drivetrain: 'RWD',
    engineConfig: 'INLINE_4_TURBO',
    displacementLiters: 2.0,
    peakHorsepower: 247,
    peakHorsepowerRpm: 6400,
    peakTorqueNm: 275,
    peakTorqueRpm: 4800,
    redlineRpm: 7500,
    idleRpm: 800,
    weightKg: 1240,
    weightDistributionFront: 0.52,
    dragCoefficient: 0.31,
    frontalAreaSqMeters: 1.95,
    downforceKgAt200Kmh: 30,
    topSpeedKmh: 240,
    zeroToHundredSec: 5.5,
    quarterMileSec: 13.9,
    fuelCapacityLiters: 65,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 296,
    brakeRotorRearMm: 258,
    brakePistonsFront: 4,
    brakePistonsRear: 1,
    tireWidthFrontMm: 205,
    tireWidthRearMm: 225,
    wheelDiameterInches: 17,
    factoryPaintColors: [
      { name: 'Lightning Yellow', hex: 0xf1c40f },
      { name: 'Brilliant Blue Pearl', hex: 0x2980b9 },
      { name: 'Super Black', hex: 0x111111 },
    ],
    description: 'SR20DET turbocharged 2.0L inline-4 paired with a helical limited-slip differential and ultra-responsive drifting steering geometry.',
    loreBiography: 'The undisputed worldwide king of professional drifting championships, beloved by grassroots drivers for its balance and agility.',
  },
  {
    id: 'veh_honda_nsx_r',
    name: 'Suzuka Type-R Midship NA',
    make: 'Suzuka',
    model: 'NSX-R NA2 Mid-Engine',
    year: 2002,
    vehicleClass: 'JDM_DRIFT',
    tier: 'S',
    priceCredits: 240000,
    unlockLevel: 28,
    drivetrain: 'RWD',
    engineConfig: 'V6_TWIN_TURBO', // V6 NA VTEC
    displacementLiters: 3.2,
    peakHorsepower: 290,
    peakHorsepowerRpm: 7300,
    peakTorqueNm: 304,
    peakTorqueRpm: 5300,
    redlineRpm: 8200,
    idleRpm: 800,
    weightKg: 1270,
    weightDistributionFront: 0.40,
    dragCoefficient: 0.30,
    frontalAreaSqMeters: 1.84,
    downforceKgAt200Kmh: 90,
    topSpeedKmh: 280,
    zeroToHundredSec: 4.4,
    quarterMileSec: 12.6,
    fuelCapacityLiters: 70,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 300,
    brakeRotorRearMm: 300,
    brakePistonsFront: 2,
    brakePistonsRear: 1,
    tireWidthFrontMm: 215,
    tireWidthRearMm: 255,
    wheelDiameterInches: 17,
    factoryPaintColors: [
      { name: 'Championship White Track', hex: 0xfbfcfc },
      { name: 'Formula Red Racing', hex: 0xc0392b },
      { name: 'Berlina Black Gloss', hex: 0x17202a },
    ],
    description: 'All-aluminum monocoque chassis tuned by Formula 1 World Champion Ayrton Senna with high-revving 3.2L V6 VTEC engine.',
    loreBiography: 'Developed to prove that a mid-engine exotic sports car could deliver supercar-beating lap times with everyday reliability.',
  },
  {
    id: 'veh_subaru_wrx_sti',
    name: 'Gunma S209 Boxer AWD',
    make: 'Gunma',
    model: 'WRX STI S209 Widebody',
    year: 2020,
    vehicleClass: 'JDM_DRIFT',
    tier: 'A',
    priceCredits: 78000,
    unlockLevel: 14,
    drivetrain: 'AWD',
    engineConfig: 'INLINE_4_TURBO', // Boxer-4 Turbo
    displacementLiters: 2.5,
    peakHorsepower: 341,
    peakHorsepowerRpm: 6200,
    peakTorqueNm: 450,
    peakTorqueRpm: 3600,
    redlineRpm: 7000,
    idleRpm: 800,
    weightKg: 1580,
    weightDistributionFront: 0.58,
    dragCoefficient: 0.35,
    frontalAreaSqMeters: 2.2,
    downforceKgAt200Kmh: 75,
    topSpeedKmh: 260,
    zeroToHundredSec: 4.4,
    quarterMileSec: 13.0,
    fuelCapacityLiters: 60,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 340,
    brakeRotorRearMm: 326,
    brakePistonsFront: 6,
    brakePistonsRear: 2,
    tireWidthFrontMm: 265,
    tireWidthRearMm: 265,
    wheelDiameterInches: 19,
    factoryPaintColors: [
      { name: 'World Rally Blue Pearl', hex: 0x1f618d },
      { name: 'Crystal White Pearl', hex: 0xf8f9f9 },
    ],
    description: 'EJ257 turbocharged Boxer-4 with Symmetrical AWD, Driver Controlled Center Differential (DCCD), and water spray intercooler.',
    loreBiography: 'Rally-bred hero engineered for gravel, snow, asphalt touge passes, and brutal off-the-line launches in all weather.',
  },
  {
    id: 'veh_mitsubishi_evo_9',
    name: 'Nagoya MR Evolution IX',
    make: 'Nagoya',
    model: 'Lancer Evolution IX MR',
    year: 2006,
    vehicleClass: 'JDM_DRIFT',
    tier: 'A',
    priceCredits: 72000,
    unlockLevel: 12,
    drivetrain: 'AWD',
    engineConfig: 'INLINE_4_TURBO',
    displacementLiters: 2.0,
    peakHorsepower: 286,
    peakHorsepowerRpm: 6500,
    peakTorqueNm: 392,
    peakTorqueRpm: 3500,
    redlineRpm: 7600,
    idleRpm: 800,
    weightKg: 1470,
    weightDistributionFront: 0.59,
    dragCoefficient: 0.34,
    frontalAreaSqMeters: 2.15,
    downforceKgAt200Kmh: 65,
    topSpeedKmh: 255,
    zeroToHundredSec: 4.5,
    quarterMileSec: 13.2,
    fuelCapacityLiters: 55,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 320,
    brakeRotorRearMm: 300,
    brakePistonsFront: 4,
    brakePistonsRear: 2,
    tireWidthFrontMm: 235,
    tireWidthRearMm: 235,
    wheelDiameterInches: 17,
    factoryPaintColors: [
      { name: 'Wicked White', hex: 0xfdfefe },
      { name: 'Tarmac Black Pearl', hex: 0x1b2631 },
      { name: 'Apex Silver Metallic', hex: 0x95a5a6 },
    ],
    description: '4G63 MIVEC turbocharged inline-4 with Super All-Wheel Control (S-AWC), Active Yaw Control (AYC), and Bilstein dampers.',
    loreBiography: 'Fierce competitor across World Rally Championship stages and asphalt time attack circuits worldwide.',
  },

  // =========================================================================
  // 3. AMERICAN MUSCLE & V8 ROAR (16-21)
  // =========================================================================
  {
    id: 'veh_dodge_hellcat',
    name: 'Detroit Phantom SRT Supercharged 6.2',
    make: 'Detroit',
    model: 'Challenger Hellcat Redeye Widebody',
    year: 2023,
    vehicleClass: 'AMERICAN_MUSCLE',
    tier: 'S',
    priceCredits: 95000,
    unlockLevel: 22,
    drivetrain: 'RWD',
    engineConfig: 'V8_SUPERCHARGED',
    displacementLiters: 6.2,
    peakHorsepower: 797,
    peakHorsepowerRpm: 6300,
    peakTorqueNm: 959,
    peakTorqueRpm: 4500,
    redlineRpm: 6500,
    idleRpm: 650,
    weightKg: 2040,
    weightDistributionFront: 0.56,
    dragCoefficient: 0.38,
    frontalAreaSqMeters: 2.5,
    downforceKgAt200Kmh: 40,
    topSpeedKmh: 327,
    zeroToHundredSec: 3.4,
    quarterMileSec: 10.8,
    fuelCapacityLiters: 70,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 390,
    brakeRotorRearMm: 350,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 305,
    tireWidthRearMm: 305,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'TorRed High Impact', hex: 0xc0392b },
      { name: 'Plum Crazy Purple', hex: 0x5b2c6f },
      { name: 'Pitch Black Metallic', hex: 0x111111 },
    ],
    description: 'Massive 2.7L twin-screw supercharger atop a 6.2L HEMI V8 generating 797 horsepower of tire-shredding American muscle.',
    loreBiography: 'Unapologetic straight-line drag strip dominance, complete with Supercharger whine and Power Chiller air-conditioning intercooler bypass.',
  },
  {
    id: 'veh_shelby_gt500',
    name: 'Dearborn Cobra GT500 Carbon Track',
    make: 'Dearborn',
    model: 'Mustang Shelby GT500 Carbon',
    year: 2022,
    vehicleClass: 'AMERICAN_MUSCLE',
    tier: 'S',
    priceCredits: 110000,
    unlockLevel: 24,
    drivetrain: 'RWD',
    engineConfig: 'V8_SUPERCHARGED',
    displacementLiters: 5.2,
    peakHorsepower: 760,
    peakHorsepowerRpm: 7300,
    peakTorqueNm: 847,
    peakTorqueRpm: 5000,
    redlineRpm: 7500,
    idleRpm: 750,
    weightKg: 1890,
    weightDistributionFront: 0.55,
    dragCoefficient: 0.35,
    frontalAreaSqMeters: 2.35,
    downforceKgAt200Kmh: 250,
    topSpeedKmh: 290,
    zeroToHundredSec: 3.3,
    quarterMileSec: 10.7,
    fuelCapacityLiters: 61,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 420,
    brakeRotorRearMm: 370,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 305,
    tireWidthRearMm: 315,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Ford Performance Blue with White Stripes', hex: 0x1b4f72 },
      { name: 'Twister Orange Tintcoat', hex: 0xd35400 },
      { name: 'Shadow Black Carbon', hex: 0x17202a },
    ],
    description: 'Cross-plane supercharged Predator 5.2L V8 backed by a Tremec 7-speed dual-clutch transmission and MagneRide active dampers.',
    loreBiography: 'Engineered to conquer road courses and drag strips alike with massive Brembo brakes and exposed carbon fiber track wheels.',
  },
  {
    id: 'veh_corvette_c8_z06',
    name: 'Bowling Green LT6 Flat-Plane Mid V8',
    make: 'Bowling Green',
    model: 'Corvette Z06 Z07 Aero Pack',
    year: 2023,
    vehicleClass: 'AMERICAN_MUSCLE',
    tier: 'S_PLUS',
    priceCredits: 145000,
    unlockLevel: 30,
    drivetrain: 'RWD',
    engineConfig: 'V8_FLATPLANE_NA',
    displacementLiters: 5.5,
    peakHorsepower: 670,
    peakHorsepowerRpm: 8400,
    peakTorqueNm: 624,
    peakTorqueRpm: 6300,
    redlineRpm: 8600,
    idleRpm: 900,
    weightKg: 1560,
    weightDistributionFront: 0.40,
    dragCoefficient: 0.36,
    frontalAreaSqMeters: 2.1,
    downforceKgAt200Kmh: 330,
    topSpeedKmh: 314,
    zeroToHundredSec: 2.6,
    quarterMileSec: 10.5,
    fuelCapacityLiters: 70,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 398,
    brakeRotorRearMm: 390,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 275,
    tireWidthRearMm: 345,
    wheelDiameterInches: 21,
    factoryPaintColors: [
      { name: 'Torch Red Supercar', hex: 0xc0392b },
      { name: 'Amplify Orange Tintcoat', hex: 0xe67e22 },
      { name: 'Hypersonic Gray Metallic', hex: 0x7f8c8d },
    ],
    description: 'Mid-engine layout with the highest-horsepower naturally aspirated production V8 in automotive history, revving to 8,600 RPM.',
    loreBiography: 'Broke with six decades of front-engine tradition to challenge European exotics on the global endurance racing stage.',
  },
  {
    id: 'veh_dodge_viper_acr',
    name: 'Detroit Snake ACR 8.4L V10',
    make: 'Detroit',
    model: 'Viper ACR Extreme Aero',
    year: 2017,
    vehicleClass: 'AMERICAN_MUSCLE',
    tier: 'S_PLUS',
    priceCredits: 180000,
    unlockLevel: 32,
    drivetrain: 'RWD',
    engineConfig: 'V10_NA',
    displacementLiters: 8.4,
    peakHorsepower: 645,
    peakHorsepowerRpm: 6200,
    peakTorqueNm: 813,
    peakTorqueRpm: 5000,
    redlineRpm: 6400,
    idleRpm: 650,
    weightKg: 1520,
    weightDistributionFront: 0.49,
    dragCoefficient: 0.48,
    frontalAreaSqMeters: 2.2,
    downforceKgAt200Kmh: 780,
    topSpeedKmh: 285,
    zeroToHundredSec: 3.3,
    quarterMileSec: 11.2,
    fuelCapacityLiters: 60,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 390,
    brakeRotorRearMm: 360,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 295,
    tireWidthRearMm: 355,
    wheelDiameterInches: 19,
    factoryPaintColors: [
      { name: 'Viper White with GTS Blue Stripes', hex: 0xf8f9f9 },
      { name: 'Competition Red ACR', hex: 0x922b21 },
      { name: 'Venom Black Carbon', hex: 0x111111 },
    ],
    description: 'Gigantic 8.4-liter naturally aspirated V10 with Bilstein 10-way racing coilovers and massive 1.8m dual-element carbon wing.',
    loreBiography: 'Held 13 simultaneous production car lap records across North American race tracks, delivering an uncompromising manual gearbox driving experience.',
  },
  {
    id: 'veh_camaro_zl1_1le',
    name: 'Bowtie Panther ZL1 1LE Extreme Track',
    make: 'Bowtie',
    model: 'Camaro ZL1 1LE Supercharged',
    year: 2023,
    vehicleClass: 'AMERICAN_MUSCLE',
    tier: 'S',
    priceCredits: 82000,
    unlockLevel: 20,
    drivetrain: 'RWD',
    engineConfig: 'V8_SUPERCHARGED',
    displacementLiters: 6.2,
    peakHorsepower: 650,
    peakHorsepowerRpm: 6400,
    peakTorqueNm: 881,
    peakTorqueRpm: 3600,
    redlineRpm: 6600,
    idleRpm: 680,
    weightKg: 1760,
    weightDistributionFront: 0.54,
    dragCoefficient: 0.37,
    frontalAreaSqMeters: 2.28,
    downforceKgAt200Kmh: 180,
    topSpeedKmh: 305,
    zeroToHundredSec: 3.5,
    quarterMileSec: 11.4,
    fuelCapacityLiters: 72,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 390,
    brakeRotorRearMm: 365,
    brakePistonsFront: 6,
    brakePistonsRear: 4,
    tireWidthFrontMm: 305,
    tireWidthRearMm: 325,
    wheelDiameterInches: 19,
    factoryPaintColors: [
      { name: 'Crush Orange Metallic', hex: 0xd35400 },
      { name: 'Rapid Blue Track', hex: 0x3498db },
      { name: 'Satin Steel Gray', hex: 0x5d6d7e },
    ],
    description: 'LT4 6.2L supercharged V8 equipped with Multimatic DSSV spool-valve dampers and front dive planes.',
    loreBiography: 'Lauded by racing instructors as one of the most capable and communicative front-engine chassis ever produced in the United States.',
  },

  // =========================================================================
  // 4. GERMAN EXECUTIVE & AUTOBAHN CRUISE (22-27)
  // =========================================================================
  {
    id: 'veh_bmw_m5_cs',
    name: 'Bavaria M5 ClubSport Twin-Turbo',
    make: 'Bavaria',
    model: 'M5 CS Lightweight V8',
    year: 2022,
    vehicleClass: 'GERMAN_EXECUTIVE',
    tier: 'S',
    priceCredits: 145000,
    unlockLevel: 26,
    drivetrain: 'AWD',
    engineConfig: 'V8_TWIN_TURBO',
    displacementLiters: 4.4,
    peakHorsepower: 627,
    peakHorsepowerRpm: 6000,
    peakTorqueNm: 750,
    peakTorqueRpm: 1800,
    redlineRpm: 7200,
    idleRpm: 700,
    weightKg: 1825,
    weightDistributionFront: 0.53,
    dragCoefficient: 0.32,
    frontalAreaSqMeters: 2.34,
    downforceKgAt200Kmh: 90,
    topSpeedKmh: 305,
    zeroToHundredSec: 2.9,
    quarterMileSec: 10.6,
    fuelCapacityLiters: 68,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 400,
    brakeRotorRearMm: 380,
    brakePistonsFront: 6,
    brakePistonsRear: 1,
    tireWidthFrontMm: 275,
    tireWidthRearMm: 285,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Frozen Deep Green Metallic', hex: 0x196f3d },
      { name: 'Frozen Brands Hatch Grey', hex: 0x566573 },
    ],
    description: 'Twin-turbo 4.4L V8 executive missile featuring M xDrive switchable RWD mode and carbon bucket seats.',
    loreBiography: 'The fastest four-door production sedan in Bavarian history, effortlessly cruising at 300+ km/h on unrestricted Autobahn corridors.',
  },
  {
    id: 'veh_mercedes_amg_e63s',
    name: 'Affalterbach E63 S V8 BiTurbo',
    make: 'Affalterbach',
    model: 'E63 S AMG 4MATIC+ Sedan',
    year: 2023,
    vehicleClass: 'GERMAN_EXECUTIVE',
    tier: 'S',
    priceCredits: 138000,
    unlockLevel: 25,
    drivetrain: 'AWD',
    engineConfig: 'V8_TWIN_TURBO',
    displacementLiters: 4.0,
    peakHorsepower: 603,
    peakHorsepowerRpm: 5750,
    peakTorqueNm: 850,
    peakTorqueRpm: 2500,
    redlineRpm: 7000,
    idleRpm: 650,
    weightKg: 2010,
    weightDistributionFront: 0.54,
    dragCoefficient: 0.30,
    frontalAreaSqMeters: 2.38,
    downforceKgAt200Kmh: 60,
    topSpeedKmh: 300,
    zeroToHundredSec: 3.1,
    quarterMileSec: 11.0,
    fuelCapacityLiters: 66,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 390,
    brakeRotorRearMm: 360,
    brakePistonsFront: 6,
    brakePistonsRear: 1,
    tireWidthFrontMm: 265,
    tireWidthRearMm: 295,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Designo Selenite Grey Magno', hex: 0x515a5a },
      { name: 'Obsidian Black Metallic', hex: 0x111111 },
      { name: 'Polar White Clearcoat', hex: 0xfdfefe },
    ],
    description: 'Handcrafted 4.0L hot-inside-V BiTurbo with 850 Nm of torque, Drift Mode decoupling, and air suspension comfort.',
    loreBiography: 'A masterclass in duality: a quiet executive boardroom on long business journeys, and a ferocious drift machine at the touch of a steering wheel button.',
  },
  {
    id: 'veh_audi_rs6_avant',
    name: 'Ingolstadt RS6 Avant Quattro Wagon',
    make: 'Ingolstadt',
    model: 'RS6 Avant Performance V8',
    year: 2024,
    vehicleClass: 'GERMAN_EXECUTIVE',
    tier: 'S',
    priceCredits: 142000,
    unlockLevel: 27,
    drivetrain: 'AWD',
    engineConfig: 'V8_TWIN_TURBO',
    displacementLiters: 4.0,
    peakHorsepower: 621,
    peakHorsepowerRpm: 6000,
    peakTorqueNm: 850,
    peakTorqueRpm: 2300,
    redlineRpm: 6800,
    idleRpm: 700,
    weightKg: 2090,
    weightDistributionFront: 0.55,
    dragCoefficient: 0.35,
    frontalAreaSqMeters: 2.45,
    downforceKgAt200Kmh: 70,
    topSpeedKmh: 305,
    zeroToHundredSec: 3.3,
    quarterMileSec: 11.3,
    fuelCapacityLiters: 73,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 420,
    brakeRotorRearMm: 370,
    brakePistonsFront: 10,
    brakePistonsRear: 1,
    tireWidthFrontMm: 285,
    tireWidthRearMm: 285,
    wheelDiameterInches: 22,
    factoryPaintColors: [
      { name: 'Nardo Grey High-Gloss', hex: 0x7f8c8d },
      { name: 'Tango Red Metallic', hex: 0x922b21 },
      { name: 'Mythos Black Metallic', hex: 0x17202a },
    ],
    description: 'Aggressive widebody estate wagon packing twin-turbo V8 firepower and permanent Quattro all-wheel-drive with sport differential.',
    loreBiography: 'The ultimate all-weather family hyper-wagon, capable of conquering snowstorms and race tracks with equal poise.',
  },

  // =========================================================================
  // 5. ELECTRIC HYPER-EVs (28-33)
  // =========================================================================
  {
    id: 'veh_rimac_nevera',
    name: 'Zagreb Nevera Quad-Motor Hyper EV',
    make: 'Zagreb',
    model: 'Nevera 1914 HP All-Electric',
    year: 2024,
    vehicleClass: 'ELECTRIC_HYPER_EV',
    tier: 'X',
    priceCredits: 2900000,
    unlockLevel: 50,
    drivetrain: 'AWD',
    engineConfig: 'QUAD_MOTOR_EV',
    displacementLiters: 0,
    peakHorsepower: 1914,
    peakHorsepowerRpm: 12000,
    peakTorqueNm: 2360,
    peakTorqueRpm: 0,
    redlineRpm: 17000,
    idleRpm: 0,
    weightKg: 2150,
    weightDistributionFront: 0.48,
    dragCoefficient: 0.30,
    frontalAreaSqMeters: 2.05,
    downforceKgAt200Kmh: 420,
    topSpeedKmh: 412,
    zeroToHundredSec: 1.85,
    quarterMileSec: 8.58,
    fuelCapacityLiters: 0,
    fuelType: 'ELECTRIC_KWH',
    electricBatteryKwh: 120,
    brakeRotorFrontMm: 390,
    brakeRotorRearMm: 390,
    brakePistonsFront: 6,
    brakePistonsRear: 6,
    tireWidthFrontMm: 275,
    tireWidthRearMm: 315,
    wheelDiameterInches: 20,
    factoryPaintColors: [
      { name: 'Signature Croatian Blue', hex: 0x1b4f72 },
      { name: 'Gunpowder Pearl Carbon', hex: 0x34495e },
      { name: 'Gloss White Storm', hex: 0xf4f6f7 },
    ],
    description: 'Four independent electric motors delivering 1,914 horsepower and instant 2,360 Nm torque vectoring at 100 calculations per second.',
    loreBiography: 'Shattered 23 world acceleration and braking records in a single day, redefining the physical boundaries of road-legal electric propulsion.',
  },
  {
    id: 'veh_tesla_model_s_plaid',
    name: 'Fremont Tri-Motor Plaid Hyper Sedan',
    make: 'Fremont',
    model: 'Cyber Plaid 1020 Tri-Motor',
    year: 2023,
    vehicleClass: 'ELECTRIC_HYPER_EV',
    tier: 'S_PLUS',
    priceCredits: 125000,
    unlockLevel: 30,
    drivetrain: 'AWD',
    engineConfig: 'TRI_MOTOR_EV',
    displacementLiters: 0,
    peakHorsepower: 1020,
    peakHorsepowerRpm: 13000,
    peakTorqueNm: 1420,
    peakTorqueRpm: 0,
    redlineRpm: 20000,
    idleRpm: 0,
    weightKg: 2160,
    weightDistributionFront: 0.50,
    dragCoefficient: 0.208,
    frontalAreaSqMeters: 2.38,
    downforceKgAt200Kmh: 40,
    topSpeedKmh: 322,
    zeroToHundredSec: 2.05,
    quarterMileSec: 9.23,
    fuelCapacityLiters: 0,
    fuelType: 'ELECTRIC_KWH',
    electricBatteryKwh: 100,
    brakeRotorFrontMm: 380,
    brakeRotorRearMm: 365,
    brakePistonsFront: 4,
    brakePistonsRear: 1,
    tireWidthFrontMm: 265,
    tireWidthRearMm: 295,
    wheelDiameterInches: 21,
    factoryPaintColors: [
      { name: 'Solid Deep Blue Metallic', hex: 0x1f618d },
      { name: 'Ultra Red Multi-Coat', hex: 0x922b21 },
      { name: 'Midnight Silver Metallic', hex: 0x5d6d7e },
    ],
    description: 'Carbon-sleeved triple rotors spinning to 20,000 RPM with the lowest drag coefficient of any production sedan on earth.',
    loreBiography: 'Capable of humbling multi-million dollar hypercars from a standstill while seating five passengers in silent comfort.',
  },
  {
    id: 'veh_porsche_taycan_turbo_s',
    name: 'Stuttgart Taycan Turbo S Dual-Motor',
    make: 'Stuttgart',
    model: 'Taycan Turbo S 800V EV',
    year: 2024,
    vehicleClass: 'ELECTRIC_HYPER_EV',
    tier: 'S_PLUS',
    priceCredits: 195000,
    unlockLevel: 34,
    drivetrain: 'AWD',
    engineConfig: 'DUAL_MOTOR_EV',
    displacementLiters: 0,
    peakHorsepower: 938,
    peakHorsepowerRpm: 11000,
    peakTorqueNm: 1110,
    peakTorqueRpm: 0,
    redlineRpm: 16000,
    idleRpm: 0,
    weightKg: 2295,
    weightDistributionFront: 0.49,
    dragCoefficient: 0.22,
    frontalAreaSqMeters: 2.33,
    downforceKgAt200Kmh: 85,
    topSpeedKmh: 260,
    zeroToHundredSec: 2.3,
    quarterMileSec: 9.8,
    fuelCapacityLiters: 0,
    fuelType: 'ELECTRIC_KWH',
    electricBatteryKwh: 105,
    brakeRotorFrontMm: 420,
    brakeRotorRearMm: 410,
    brakePistonsFront: 10,
    brakePistonsRear: 4,
    tireWidthFrontMm: 265,
    tireWidthRearMm: 305,
    wheelDiameterInches: 21,
    factoryPaintColors: [
      { name: 'Neptune Blue Gloss', hex: 0x2471a3 },
      { name: 'Carmine Red', hex: 0xc0392b },
      { name: 'Volcano Grey Metallic', hex: 0x34495e },
    ],
    description: '800-volt high-speed charging architecture paired with a unique 2-speed rear axle transmission for unmatched launch endurance.',
    loreBiography: 'Engineered with legendary German chassis dynamics to provide repeatable, non-degrading launch control sprints all day long.',
  },

  // =========================================================================
  // 6. OFF-ROAD & 4X4 TRAIL BLAZERS (34-39)
  // =========================================================================
  {
    id: 'veh_ford_raptor_r',
    name: 'Dearborn Raptor-R 5.2 Supercharged V8',
    make: 'Dearborn',
    model: 'F-150 Raptor R 4x4',
    year: 2023,
    vehicleClass: 'OFFROAD_4X4',
    tier: 'A',
    priceCredits: 115000,
    unlockLevel: 20,
    drivetrain: '4WD',
    engineConfig: 'V8_SUPERCHARGED',
    displacementLiters: 5.2,
    peakHorsepower: 700,
    peakHorsepowerRpm: 6650,
    peakTorqueNm: 868,
    peakTorqueRpm: 4250,
    redlineRpm: 7000,
    idleRpm: 700,
    weightKg: 2700,
    weightDistributionFront: 0.58,
    dragCoefficient: 0.52,
    frontalAreaSqMeters: 3.4,
    downforceKgAt200Kmh: -20,
    topSpeedKmh: 190,
    zeroToHundredSec: 3.7,
    quarterMileSec: 12.1,
    fuelCapacityLiters: 136,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 350,
    brakeRotorRearMm: 336,
    brakePistonsFront: 2,
    brakePistonsRear: 1,
    tireWidthFrontMm: 315,
    tireWidthRearMm: 315,
    wheelDiameterInches: 17,
    factoryPaintColors: [
      { name: 'Avalanche Grey Clear', hex: 0xd5dbdb },
      { name: 'Code Orange Metallic', hex: 0xd35400 },
      { name: 'Antimatter Blue Metallic', hex: 0x1b2631 },
    ],
    description: 'Fox Live Valve 3.1 internal bypass shocks with 37-inch all-terrain tires and supercharged V8 desert-racing suspension travel.',
    loreBiography: 'Built to leap sand dunes at 160 km/h in Baja 1000 desert endurance races without breaking a sweat.',
  },
  {
    id: 'veh_ram_trx',
    name: 'Detroit Rex TRX 6.2 Supercharged',
    make: 'Detroit',
    model: '1500 TRX Launch Edition',
    year: 2022,
    vehicleClass: 'OFFROAD_4X4',
    tier: 'A',
    priceCredits: 98000,
    unlockLevel: 18,
    drivetrain: '4WD',
    engineConfig: 'V8_SUPERCHARGED',
    displacementLiters: 6.2,
    peakHorsepower: 702,
    peakHorsepowerRpm: 6100,
    peakTorqueNm: 881,
    peakTorqueRpm: 4800,
    redlineRpm: 6400,
    idleRpm: 680,
    weightKg: 2880,
    weightDistributionFront: 0.57,
    dragCoefficient: 0.54,
    frontalAreaSqMeters: 3.5,
    downforceKgAt200Kmh: -30,
    topSpeedKmh: 190,
    zeroToHundredSec: 3.9,
    quarterMileSec: 12.3,
    fuelCapacityLiters: 125,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 381,
    brakeRotorRearMm: 381,
    brakePistonsFront: 2,
    brakePistonsRear: 1,
    tireWidthFrontMm: 325,
    tireWidthRearMm: 325,
    wheelDiameterInches: 18,
    factoryPaintColors: [
      { name: 'Anvil Clear-Coat Gray', hex: 0x566573 },
      { name: 'Ignition Orange', hex: 0xe67e22 },
      { name: 'Diamond Black Crystal', hex: 0x111111 },
    ],
    description: 'Heavyweight desert apex predator with Bilstein Black Hawk e2 adaptive dampers and supercharged V8 soundtrack.',
    loreBiography: 'Dominates muddy trails and rugged terrain with full-time 4WD transfer case and reinforced hydroformed steel frame.',
  },
  {
    id: 'veh_mercedes_g63',
    name: 'Stuttgart Gelande G63 AMG BiTurbo',
    make: 'Stuttgart',
    model: 'G63 AMG 4x4 Squared',
    year: 2023,
    vehicleClass: 'OFFROAD_4X4',
    tier: 'S',
    priceCredits: 220000,
    unlockLevel: 30,
    drivetrain: '4WD',
    engineConfig: 'V8_TWIN_TURBO',
    displacementLiters: 4.0,
    peakHorsepower: 577,
    peakHorsepowerRpm: 6000,
    peakTorqueNm: 850,
    peakTorqueRpm: 2500,
    redlineRpm: 7000,
    idleRpm: 650,
    weightKg: 2560,
    weightDistributionFront: 0.52,
    dragCoefficient: 0.54,
    frontalAreaSqMeters: 3.1,
    downforceKgAt200Kmh: -10,
    topSpeedKmh: 240,
    zeroToHundredSec: 4.2,
    quarterMileSec: 12.7,
    fuelCapacityLiters: 100,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 400,
    brakeRotorRearMm: 370,
    brakePistonsFront: 6,
    brakePistonsRear: 1,
    tireWidthFrontMm: 295,
    tireWidthRearMm: 295,
    wheelDiameterInches: 22,
    factoryPaintColors: [
      { name: 'G Manufaktur Olive Metallic', hex: 0x1e8449 },
      { name: 'Desert Sand Matte', hex: 0xd4ac0d },
      { name: 'Obsidian Black', hex: 0x111111 },
    ],
    description: 'Military-derived ladder frame chassis equipped with three 100% locking differentials and side-exit exhaust pipes.',
    loreBiography: 'Originally commissioned for world defense forces, now celebrated as the ultimate luxury high-clearance off-road status symbol.',
  },

  // =========================================================================
  // 7. COMMERCIAL LOGISTICS & HEAVY FREIGHT (40-45)
  // =========================================================================
  {
    id: 'veh_peterbilt_389',
    name: 'Denton LongHaul 389 Classic Heavy Semi',
    make: 'Denton',
    model: 'LongHaul 389 Sleeper Cab 18-Wheeler',
    year: 2023,
    vehicleClass: 'COMMERCIAL_HAULER',
    tier: 'B',
    priceCredits: 175000,
    unlockLevel: 15,
    drivetrain: 'RWD',
    engineConfig: 'HEAVY_INLINE_6_TURBODIESEL',
    displacementLiters: 15.0,
    peakHorsepower: 605,
    peakHorsepowerRpm: 1800,
    peakTorqueNm: 2780,
    peakTorqueRpm: 1150,
    redlineRpm: 2200,
    idleRpm: 600,
    weightKg: 8900,
    weightDistributionFront: 0.35,
    dragCoefficient: 0.70,
    frontalAreaSqMeters: 8.5,
    downforceKgAt200Kmh: 0,
    topSpeedKmh: 135,
    zeroToHundredSec: 14.5,
    quarterMileSec: 21.0,
    fuelCapacityLiters: 600,
    fuelType: 'DIESEL',
    brakeRotorFrontMm: 430,
    brakeRotorRearMm: 430,
    brakePistonsFront: 4,
    brakePistonsRear: 4,
    tireWidthFrontMm: 295,
    tireWidthRearMm: 295,
    wheelDiameterInches: 24.5,
    factoryPaintColors: [
      { name: 'Midnight Chrome & Crimson', hex: 0x78281f },
      { name: 'Royal Navy Metallic Blue', hex: 0x1b4f72 },
      { name: 'High-Gloss Classic Black', hex: 0x111111 },
    ],
    description: 'Iconic long-nose American conventional tractor with Cummins X15 turbodiesel and 18-speed manual Eaton Fuller roadranger transmission.',
    loreBiography: 'The undisputed backbone of continental interstate freight logistics, capable of pulling 40-ton loaded cargo trailers across mountain passes.',
  },
  {
    id: 'veh_scania_770s',
    name: 'Sodertalje King 770 S V8 Heavy Hauler',
    make: 'Sodertalje',
    model: '770 S V8 Highline Cab',
    year: 2024,
    vehicleClass: 'COMMERCIAL_HAULER',
    tier: 'A',
    priceCredits: 210000,
    unlockLevel: 22,
    drivetrain: 'RWD',
    engineConfig: 'V8_TURBODIESEL',
    displacementLiters: 16.4,
    peakHorsepower: 770,
    peakHorsepowerRpm: 1800,
    peakTorqueNm: 3700,
    peakTorqueRpm: 1000,
    redlineRpm: 2400,
    idleRpm: 550,
    weightKg: 8400,
    weightDistributionFront: 0.40,
    dragCoefficient: 0.58,
    frontalAreaSqMeters: 8.2,
    downforceKgAt200Kmh: 0,
    topSpeedKmh: 145,
    zeroToHundredSec: 12.0,
    quarterMileSec: 18.5,
    fuelCapacityLiters: 800,
    fuelType: 'DIESEL',
    brakeRotorFrontMm: 434,
    brakeRotorRearMm: 434,
    brakePistonsFront: 4,
    brakePistonsRear: 4,
    tireWidthFrontMm: 315,
    tireWidthRearMm: 315,
    wheelDiameterInches: 22.5,
    factoryPaintColors: [
      { name: 'King of the Road Ruby Red', hex: 0x922b21 },
      { name: 'Frozen Silver Metallic', hex: 0xbdc3c7 },
      { name: 'Deep Sea Blue', hex: 0x1f618d },
    ],
    description: 'The most powerful production truck in Europe, producing a gargantuan 3,700 Nm of low-end torque from a 16.4L V8 turbodiesel.',
    loreBiography: 'Engineered for exceptional driver ergonomics, luxury living quarters, and extreme heavy-haul oversized transport convoys.',
  },

  // =========================================================================
  // 8. URBAN MASS TRANSIT & FLEET (46-50)
  // =========================================================================
  {
    id: 'veh_city_transit_bus',
    name: 'Metro CityLink 40ft Low-Floor Bus',
    make: 'MetroLink',
    model: 'Transit Low-Floor 40',
    year: 2023,
    vehicleClass: 'URBAN_TRANSIT',
    tier: 'C',
    priceCredits: 125000,
    unlockLevel: 8,
    drivetrain: 'RWD',
    engineConfig: 'HEAVY_INLINE_6_TURBODIESEL',
    displacementLiters: 8.9,
    peakHorsepower: 330,
    peakHorsepowerRpm: 2000,
    peakTorqueNm: 1350,
    peakTorqueRpm: 1200,
    redlineRpm: 2400,
    idleRpm: 600,
    weightKg: 12800,
    weightDistributionFront: 0.38,
    dragCoefficient: 0.65,
    frontalAreaSqMeters: 7.8,
    downforceKgAt200Kmh: 0,
    topSpeedKmh: 105,
    zeroToHundredSec: 17.5,
    quarterMileSec: 23.5,
    fuelCapacityLiters: 450,
    fuelType: 'DIESEL',
    brakeRotorFrontMm: 410,
    brakeRotorRearMm: 410,
    brakePistonsFront: 2,
    brakePistonsRear: 2,
    tireWidthFrontMm: 275,
    tireWidthRearMm: 275,
    wheelDiameterInches: 22.5,
    factoryPaintColors: [
      { name: 'Metro Municipal Transit Blue', hex: 0x2980b9 },
      { name: 'Eco Transit Green', hex: 0x27ae60 },
      { name: 'Rapid Airport Express Yellow', hex: 0xf39c12 },
    ],
    description: '40-passenger municipal transit bus with pneumatic kneeling suspension, dual automatic sliding doors, and Allison automatic transmission.',
    loreBiography: 'Transports millions of daily commuters through downtown avenues and airport transfer terminals on tight schedules.',
  },
  {
    id: 'veh_sprinter_cargo_van',
    name: 'Stuttgart TransMax High-Roof Courier',
    make: 'Stuttgart',
    model: 'Sprinter 3500 Cargo XL',
    year: 2023,
    vehicleClass: 'URBAN_TRANSIT',
    tier: 'C',
    priceCredits: 58000,
    unlockLevel: 5,
    drivetrain: 'RWD',
    engineConfig: 'INLINE_4_TURBO',
    displacementLiters: 2.0,
    peakHorsepower: 211,
    peakHorsepowerRpm: 3800,
    peakTorqueNm: 450,
    peakTorqueRpm: 1600,
    redlineRpm: 4500,
    idleRpm: 750,
    weightKg: 2450,
    weightDistributionFront: 0.52,
    dragCoefficient: 0.38,
    frontalAreaSqMeters: 4.2,
    downforceKgAt200Kmh: 0,
    topSpeedKmh: 165,
    zeroToHundredSec: 8.8,
    quarterMileSec: 16.5,
    fuelCapacityLiters: 93,
    fuelType: 'DIESEL',
    brakeRotorFrontMm: 300,
    brakeRotorRearMm: 298,
    brakePistonsFront: 2,
    brakePistonsRear: 1,
    tireWidthFrontMm: 215,
    tireWidthRearMm: 215,
    wheelDiameterInches: 16,
    factoryPaintColors: [
      { name: 'Arctic Fleet White', hex: 0xfafafa },
      { name: 'Express Courier Yellow', hex: 0xf1c40f },
      { name: 'Graphite Grey Metallic', hex: 0x34495e },
    ],
    description: 'High-payload commercial parcel carrier with 15 cubic meters of cargo volume and 9-speed automatic transmission.',
    loreBiography: 'The preferred workhorse for express delivery careers, medical supply couriers, and high-value cargo runs.',
  },

  // =========================================================================
  // 9. VINTAGE CLASSIC & RETRO THOROUGHBREDS (51-54)
  // =========================================================================
  {
    id: 'veh_shelby_cobra_427',
    name: 'Venice Cobra 427 S/C Roadster',
    make: 'Venice',
    model: 'Shelby Cobra 427 Competition',
    year: 1965,
    vehicleClass: 'VINTAGE_CLASSIC',
    tier: 'S',
    priceCredits: 1200000,
    unlockLevel: 42,
    drivetrain: 'RWD',
    engineConfig: 'V8_CROSSPLANE_NA',
    displacementLiters: 7.0,
    peakHorsepower: 485,
    peakHorsepowerRpm: 6500,
    peakTorqueNm: 651,
    peakTorqueRpm: 3700,
    redlineRpm: 7000,
    idleRpm: 850,
    weightKg: 1060,
    weightDistributionFront: 0.49,
    dragCoefficient: 0.45,
    frontalAreaSqMeters: 1.68,
    downforceKgAt200Kmh: 10,
    topSpeedKmh: 265,
    zeroToHundredSec: 4.1,
    quarterMileSec: 12.2,
    fuelCapacityLiters: 76,
    fuelType: 'RACING_110_OCTANE',
    brakeRotorFrontMm: 292,
    brakeRotorRearMm: 273,
    brakePistonsFront: 2,
    brakePistonsRear: 1,
    tireWidthFrontMm: 245,
    tireWidthRearMm: 295,
    wheelDiameterInches: 15,
    factoryPaintColors: [
      { name: 'Guardsman Blue with White Racing Stripes', hex: 0x1b4f72 },
      { name: 'Wimbledon White with Blue Stripes', hex: 0xfdfefe },
      { name: 'Raven Black', hex: 0x111111 },
    ],
    description: 'Raw aluminum body roadster with a massive 427 cubic-inch (7.0L) FE side-oiler V8 and zero electronic assists.',
    loreBiography: 'Built by Carroll Shelby to slay European GT prototypes. One of the rawest, loudest, and most legendary muscle roadsters ever built.',
  },
  {
    id: 'veh_dodge_charger_1970',
    name: 'Detroit 1970 426 HEMI R/T Hardtop',
    make: 'Detroit',
    model: 'Charger R/T 426 HEMI',
    year: 1970,
    vehicleClass: 'VINTAGE_CLASSIC',
    tier: 'A',
    priceCredits: 280000,
    unlockLevel: 25,
    drivetrain: 'RWD',
    engineConfig: 'V8_CROSSPLANE_NA',
    displacementLiters: 7.0,
    peakHorsepower: 425,
    peakHorsepowerRpm: 5000,
    peakTorqueNm: 664,
    peakTorqueRpm: 4000,
    redlineRpm: 6000,
    idleRpm: 750,
    weightKg: 1780,
    weightDistributionFront: 0.56,
    dragCoefficient: 0.42,
    frontalAreaSqMeters: 2.3,
    downforceKgAt200Kmh: 0,
    topSpeedKmh: 240,
    zeroToHundredSec: 5.2,
    quarterMileSec: 13.5,
    fuelCapacityLiters: 72,
    fuelType: 'GASOLINE_98',
    brakeRotorFrontMm: 279,
    brakeRotorRearMm: 254,
    brakePistonsFront: 1,
    brakePistonsRear: 1,
    tireWidthFrontMm: 235,
    tireWidthRearMm: 255,
    wheelDiameterInches: 15,
    factoryPaintColors: [
      { name: 'Tuxedo Black Gloss', hex: 0x111111 },
      { name: 'Go Mango Orange', hex: 0xd35400 },
      { name: 'Sub-Lime High Impact Green', hex: 0x27ae60 },
    ],
    description: 'The golden age of American muscle with dual four-barrel carburetors, Dana 60 rear axle, and iconic hidden headlights.',
    loreBiography: 'Immortalized in cinema and street folklore as the ultimate outlaw street machine.',
  },
];

export class VehicleCatalog {
  private static catalogMap: Map<string, VehicleCatalogEntry> = new Map(
    VEHICLE_CATALOG_DATA.map((entry) => [entry.id, entry])
  );

  public static getAllVehicles(): VehicleCatalogEntry[] {
    return VEHICLE_CATALOG_DATA;
  }

  public static getVehicleById(id: string): VehicleCatalogEntry | undefined {
    return this.catalogMap.get(id);
  }

  public static getVehiclesByClass(vClass: VehicleClass): VehicleCatalogEntry[] {
    return VEHICLE_CATALOG_DATA.filter((v) => v.vehicleClass === vClass);
  }

  public static getVehiclesByTier(tier: PerformanceTier): VehicleCatalogEntry[] {
    return VEHICLE_CATALOG_DATA.filter((v) => v.tier === tier);
  }

  public static getVehiclesByDrivetrain(dt: DrivetrainLayout): VehicleCatalogEntry[] {
    return VEHICLE_CATALOG_DATA.filter((v) => v.drivetrain === dt);
  }

  public static filterVehicles(query: {
    minPrice?: number;
    maxPrice?: number;
    vehicleClass?: VehicleClass;
    tier?: PerformanceTier;
    drivetrain?: DrivetrainLayout;
    maxLevel?: number;
  }): VehicleCatalogEntry[] {
    return VEHICLE_CATALOG_DATA.filter((v) => {
      if (query.minPrice !== undefined && v.priceCredits < query.minPrice) return false;
      if (query.maxPrice !== undefined && v.priceCredits > query.maxPrice) return false;
      if (query.vehicleClass && v.vehicleClass !== query.vehicleClass) return false;
      if (query.tier && v.tier !== query.tier) return false;
      if (query.drivetrain && v.drivetrain !== query.drivetrain) return false;
      if (query.maxLevel !== undefined && v.unlockLevel > query.maxLevel) return false;
      return true;
    });
  }
}
