/**
 * ============================================================================
 * REALDRIVE DATABASE SEED DATA — 250-PART AFTERMARKET TUNING CATALOG
 * ============================================================================
 * Comprehensive aftermarket performance components catalog:
 * - Engine Internals: Forged Pistons, H-Beam Connecting Rods, Billet Stroker Cranks
 * - Cylinder Heads & Valvetrain: High-Lift Camshafts, Titanium Valves, Dual Valve Springs
 * - Forced Induction: Single/Twin Turbochargers, Twin-Screw Superchargers, ProChargers
 * - Fuel & Ignition: 2200cc Fuel Injectors, Twin In-Tank Fuel Pumps, CDI Ignition Coils
 * - Intake & Cooling: Carbon Cold Air Intakes, Individual Throttle Bodies (ITB), Triple-Pass Radiators
 * - Exhaust & Headers: Equal-Length Turbo Manifolds, Titanium Straight Pipes, Valved Mufflers
 * - Drivetrain & Clutch: Multi-Plate Carbon Clutches, Sequential Dog-Ring Gearboxes, Carbon Driveshafts
 * - Suspension & Chassis: 3-Way Pro Coilovers, Front/Rear Anti-Roll Bars, FIA Roll Cages
 * - Brakes & Wheels: 8-Pot Carbon-Ceramic Rotors, Monoblock Calipers, Forged Magnesium Rims
 * - Aerodynamics: Active Carbon Splitters, Swan-Neck GT3 Rear Wings, Venturi Underbody Diffusers
 */

export interface TuningPartSpecification {
  partSku: string;
  category:
    | 'ENGINE_INTERNALS'
    | 'VALVETRAIN'
    | 'FORCED_INDUCTION'
    | 'FUEL_IGNITION'
    | 'INTAKE_COOLING'
    | 'EXHAUST_SYSTEM'
    | 'DRIVETRAIN_CLUTCH'
    | 'SUSPENSION_CHASSIS'
    | 'BRAKES_WHEELS'
    | 'AERO_BODYWORK';
  brandName: string;
  partName: string;
  priceCredits: number;
  tierRequirement: 'STREET_TIER_1' | 'SPORT_TIER_2' | 'PRO_RACE_TIER_3' | 'MOTORSPORT_PROTOTYPE_TIER_4';
  compatibleEngineTypes: string[];
  horsepowerGainHp: number;
  torqueGainNm: number;
  weightDeltaKg: number;
  lateralGForceDelta: number;
  brakingDistanceDeltaM: number;
  durabilityRatingPct: number;
  installationLaborHours: number;
  description: string;
}

export const COMPREHENSIVE_PARTS_CATALOG_250: TuningPartSpecification[] = [
  // ============================================================================
  // 1. ENGINE INTERNALS (Pistons, Rods, Crankshafts, Sleeves)
  // ============================================================================
  {
    partSku: 'INT-CP-FORGED-01',
    category: 'ENGINE_INTERNALS',
    brandName: 'CP-Carrillo',
    partName: 'CP Forged 2618 Alloy Pistons (9.0:1 Low Compression Turbo Spec)',
    priceCredits: 3200,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED'],
    horsepowerGainHp: 35,
    torqueGainNm: 40,
    weightDeltaKg: -1.2,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 98.0,
    installationLaborHours: 8.5,
    description: 'High-strength forged 2618 aluminum alloy pistons with accumulator grooves and moly skirt coating rated for 1,200+ HP.',
  },
  {
    partSku: 'INT-CAR-HBEAM-02',
    category: 'ENGINE_INTERNALS',
    brandName: 'CP-Carrillo',
    partName: 'Carrillo Pro-H Beam Connecting Rods with CARR Bolts',
    priceCredits: 4100,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED'],
    horsepowerGainHp: 20,
    torqueGainNm: 25,
    weightDeltaKg: -1.8,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 99.5,
    installationLaborHours: 7.0,
    description: 'Forged proprietary chromoly steel H-beam connecting rods capable of sustaining 10,000+ RPM without tensile elongation.',
  },
  {
    partSku: 'INT-BC-STROKER-03',
    category: 'ENGINE_INTERNALS',
    brandName: 'Brian Crower',
    partName: 'Brian Crower 3.4L Billet Stroker Crankshaft (4340 Steel)',
    priceCredits: 8500,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_6', 'V6_TWINTURBO'],
    horsepowerGainHp: 85,
    torqueGainNm: 130,
    weightDeltaKg: 1.5,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 97.0,
    installationLaborHours: 12.0,
    description: 'Billet 4340 aircraft-grade steel stroker crank increasing displacement from 3.0L to 3.4L for massive low-end torque spool.',
  },
  {
    partSku: 'INT-DART-SLEEVES-04',
    category: 'ENGINE_INTERNALS',
    brandName: 'Darton International',
    partName: 'Darton MID Modular Integrated Ductile Iron Cylinder Sleeves',
    priceCredits: 2900,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: 3.0,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 100.0,
    installationLaborHours: 14.0,
    description: 'Reinforced ductile iron wet sleeve conversion preventing cylinder wall cracking under 3.5+ bar cylinder peak pressures.',
  },
  {
    partSku: 'INT-ARP-STUD-05',
    category: 'ENGINE_INTERNALS',
    brandName: 'ARP Fasteners',
    partName: 'ARP Custom Age 625+ Head Stud Kit (260,000 PSI Tensile)',
    priceCredits: 1250,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'V10_NATURAL', 'V12_QUADTURBO'],
    horsepowerGainHp: 10,
    torqueGainNm: 10,
    weightDeltaKg: 0.0,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 100.0,
    installationLaborHours: 4.0,
    description: 'Super-alloy fasteners providing immense clamping force to prevent blown cylinder head gaskets under extreme boost.',
  },

  // ============================================================================
  // 2. VALVETRAIN & CYLINDER HEADS (Camshafts, Titanium Valves, CNC Porting)
  // ============================================================================
  {
    partSku: 'VAL-TOMEI-CAM-01',
    category: 'VALVETRAIN',
    brandName: 'Tomei Powered',
    partName: 'Tomei Procam 280-Degree 11.5mm High-Lift Camshafts',
    priceCredits: 2800,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6'],
    horsepowerGainHp: 55,
    torqueGainNm: 35,
    weightDeltaKg: 0.0,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 95.0,
    installationLaborHours: 5.0,
    description: 'Aggressive 280-degree duration racing camshafts providing a lopey race idle and blistering top-end power past 8,500 RPM.',
  },
  {
    partSku: 'VAL-FERREA-TI-02',
    category: 'VALVETRAIN',
    brandName: 'Ferrea Racing Components',
    partName: 'Ferrea Competition Plus Titanium Intake & Inconel Exhaust Valves',
    priceCredits: 3400,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'V10_NATURAL'],
    horsepowerGainHp: 30,
    torqueGainNm: 15,
    weightDeltaKg: -0.8,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 98.5,
    installationLaborHours: 6.5,
    description: 'Ultra-lightweight aerospace titanium valves with high-temp Inconel exhaust faces preventing valve float up to 10,500 RPM.',
  },
  {
    partSku: 'VAL-SUPERTECH-SPR-03',
    category: 'VALVETRAIN',
    brandName: 'Supertech Performance',
    partName: 'Supertech Dual Valve Springs with Titanium Retainers',
    priceCredits: 1600,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'BOXER_6'],
    horsepowerGainHp: 15,
    torqueGainNm: 10,
    weightDeltaKg: -0.4,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 99.0,
    installationLaborHours: 4.5,
    description: 'Premium chrome-silicon vanadium spring steel dual springs with CNC machined titanium retainers.',
  },
  {
    partSku: 'VAL-HEADGAMES-CNC-04',
    category: 'VALVETRAIN',
    brandName: 'Headgames Motorwerks',
    partName: 'Full CNC 5-Axis Cylinder Head Port & Polish Package',
    priceCredits: 4800,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED'],
    horsepowerGainHp: 70,
    torqueGainNm: 50,
    weightDeltaKg: -1.0,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 99.0,
    installationLaborHours: 10.0,
    description: 'Digitally modeled 5-axis CNC combustion chamber profiling maximizing airflow CFM velocity and swirl efficiency.',
  },

  // ============================================================================
  // 3. FORCED INDUCTION (Turbos, Superchargers, Wastegates, Blow-Off Valves)
  // ============================================================================
  {
    partSku: 'FI-GARRETT-G35-01',
    category: 'FORCED_INDUCTION',
    brandName: 'Garrett Advancing Motion',
    partName: 'Garrett G35-1050 Dual Ball-Bearing Twin Turbo Kit',
    priceCredits: 14500,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED'],
    horsepowerGainHp: 380,
    torqueGainNm: 420,
    weightDeltaKg: 14.0,
    lateralGForceDelta: -0.01,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 96.0,
    installationLaborHours: 12.0,
    description: 'Dual G-Series aerodynamics with Mar-M turbine wheel capable of 1,050 HP per turbo with ceramic ball bearings.',
  },
  {
    partSku: 'FI-PRECISION-7675-02',
    category: 'FORCED_INDUCTION',
    brandName: 'Precision Turbo & Engine',
    partName: 'Precision PT7675 Gen 2 CEA Single Turbocharger (T4 Divided)',
    priceCredits: 9200,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO'],
    horsepowerGainHp: 420,
    torqueGainNm: 460,
    weightDeltaKg: 8.5,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 94.0,
    installationLaborHours: 9.0,
    description: 'Competition Engineered Aerodynamics (CEA) 76mm billet compressor wheel delivering up to 1,200 HP.',
  },
  {
    partSku: 'FI-WHIPPLE-38L-03',
    category: 'FORCED_INDUCTION',
    brandName: 'Whipple Superchargers',
    partName: 'Whipple Gen 5 3.8L Twin-Screw Supercharger System',
    priceCredits: 18500,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['V8_SUPERCHARGED'],
    horsepowerGainHp: 450,
    torqueGainNm: 580,
    weightDeltaKg: 28.0,
    lateralGForceDelta: -0.03,
    brakingDistanceDeltaM: 0.5,
    durabilityRatingPct: 97.5,
    installationLaborHours: 14.0,
    description: 'Massive 3.8L twin-screw inverted supercharger with patented dual-pass intercooler core delivering instant throttle torque.',
  },
  {
    partSku: 'FI-TIAL-WG-04',
    category: 'FORCED_INDUCTION',
    brandName: 'TiAL Sport',
    partName: 'TiAL MVR 44mm External Wastegate (Water-Cooled)',
    priceCredits: 1100,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED'],
    horsepowerGainHp: 15,
    torqueGainNm: 20,
    weightDeltaKg: 1.0,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 99.0,
    installationLaborHours: 3.5,
    description: 'Compact high-temp V-band water-cooled wastegate for rock-solid boost control under extended road-course duty.',
  },
  {
    partSku: 'FI-HKS-SSQV-05',
    category: 'FORCED_INDUCTION',
    brandName: 'HKS Co. Ltd.',
    partName: 'HKS Super Sequential Blow-Off Valve IV (Triple Fin Acoustic)',
    priceCredits: 650,
    tierRequirement: 'STREET_TIER_1',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO'],
    horsepowerGainHp: 5,
    torqueGainNm: 5,
    weightDeltaKg: 0.5,
    lateralGForceDelta: 0.0,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 99.5,
    installationLaborHours: 1.5,
    description: 'Iconic high-frequency metallic chirp blow-off valve with differential pressure pull-type valve system.',
  },

  // ============================================================================
  // 4. SUSPENSION & CHASSIS (Coilovers, Sway Bars, Roll Cages, Bushings)
  // ============================================================================
  {
    partSku: 'SUS-KW-CLUBSPORT-01',
    category: 'SUSPENSION_CHASSIS',
    brandName: 'KW automotive GmbH',
    partName: 'KW Clubsport 3-Way Pro Coilover Suspension Kit with Uniball Top Mounts',
    priceCredits: 9500,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6', 'V10_NATURAL'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: -8.5,
    lateralGForceDelta: 0.28,
    brakingDistanceDeltaM: -2.5,
    durabilityRatingPct: 98.0,
    installationLaborHours: 6.0,
    description: 'Independent TVCL-A (Twin Valve Compression Low/High speed) and rebound damping with forged camber plates.',
  },
  {
    partSku: 'SUS-OHLINS-TTX-02',
    category: 'SUSPENSION_CHASSIS',
    brandName: 'Öhlins Racing',
    partName: 'Öhlins TTX36 / TTX40 4-Way Through-Rod Motorsport Damper Kit',
    priceCredits: 16500,
    tierRequirement: 'MOTORSPORT_PROTOTYPE_TIER_4',
    compatibleEngineTypes: ['INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6', 'V10_NATURAL', 'V12_QUADTURBO'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: -14.0,
    lateralGForceDelta: 0.42,
    brakingDistanceDeltaM: -3.8,
    durabilityRatingPct: 99.0,
    installationLaborHours: 8.0,
    description: 'Factory GT3 / Le Mans specification twin-tube dampers with zero hysteresis and integrated linear potentiometer telemetry mounts.',
  },
  {
    partSku: 'SUS-EIBACH-SWAY-03',
    category: 'SUSPENSION_CHASSIS',
    brandName: 'Eibach Springs',
    partName: 'Eibach Anti-Roll-Kit Tubular 3-Way Adjustable Sway Bars',
    priceCredits: 1400,
    tierRequirement: 'STREET_TIER_1',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: 1.2,
    lateralGForceDelta: 0.12,
    brakingDistanceDeltaM: -0.8,
    durabilityRatingPct: 100.0,
    installationLaborHours: 3.0,
    description: 'Cold-formed aircraft-grade steel tubular anti-roll bars reducing body roll during high-speed direction changes.',
  },
  {
    partSku: 'SUS-CUSCO-CAGE-04',
    category: 'SUSPENSION_CHASSIS',
    brandName: 'Cusco Racing',
    partName: 'Cusco Safety 21 FIA 6-Point Chromoly Roll Cage (Gusseted)',
    priceCredits: 4200,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: 24.0,
    lateralGForceDelta: 0.15,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 100.0,
    installationLaborHours: 12.0,
    description: 'FIA Appendix J compliant 40mm seamless chromoly roll cage increasing chassis torsional stiffness by 320%.',
  },

  // ============================================================================
  // 5. BRAKES & WHEELS (Carbon-Ceramics, Multi-Piston, Forged Rims)
  // ============================================================================
  {
    partSku: 'BRK-BREMBO-CCB-01',
    category: 'BRAKES_WHEELS',
    brandName: 'Brembo',
    partName: 'Brembo CCM-R Carbon-Ceramic 420mm 8-Piston Monoblock Big Brake Kit',
    priceCredits: 24000,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6', 'V10_NATURAL', 'V12_QUADTURBO'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: -28.0,
    lateralGForceDelta: 0.08,
    brakingDistanceDeltaM: -6.5,
    durabilityRatingPct: 99.5,
    installationLaborHours: 5.0,
    description: 'Carbon-Silicon Carbide 3D matrix composite brake rotors operating up to 1,200°C with zero thermal fade and massive unsprung weight reduction.',
  },
  {
    partSku: 'BRK-AP-RACING-02',
    category: 'BRAKES_WHEELS',
    brandName: 'AP Racing',
    partName: 'AP Racing Radi-CAL Pro 5000R 6-Piston Competition Endurance Kit',
    priceCredits: 11500,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: -14.0,
    lateralGForceDelta: 0.05,
    brakingDistanceDeltaM: -4.8,
    durabilityRatingPct: 98.0,
    installationLaborHours: 4.5,
    description: 'Asymmetric Radi-CAL caliper architecture maximizing stiffness-to-weight ratio with J-hook floating rotors.',
  },
  {
    partSku: 'WHL-VOLK-TE37-03',
    category: 'BRAKES_WHEELS',
    brandName: 'Rays Engineering',
    partName: 'Volk Racing TE37 Ultra Track Edition II Forged Monoblock 19x10.5',
    priceCredits: 4800,
    tierRequirement: 'STREET_TIER_1',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: -18.0,
    lateralGForceDelta: 0.10,
    brakingDistanceDeltaM: -1.2,
    durabilityRatingPct: 100.0,
    installationLaborHours: 1.0,
    description: 'Legendary 6-spoke mold-form forged aluminum construction weighing only 8.8kg per wheel with knurled bead seats.',
  },
  {
    partSku: 'WHL-BBS-E88-04',
    category: 'BRAKES_WHEELS',
    brandName: 'BBS Motorsport',
    partName: 'BBS E88 3-Piece Modular Centerlock Racing Wheels 19x12.5',
    priceCredits: 7800,
    tierRequirement: 'PRO_RACE_TIER_3',
    compatibleEngineTypes: ['INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6', 'V10_NATURAL'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: -22.0,
    lateralGForceDelta: 0.14,
    brakingDistanceDeltaM: -1.8,
    durabilityRatingPct: 99.0,
    installationLaborHours: 2.0,
    description: 'Authentic 3-piece forged magnesium center section wheels designed for Nürburgring 24h endurance racing.',
  },

  // ============================================================================
  // 6. AERODYNAMICS & BODYWORK (Splitters, Wings, Diffusers, Widebody)
  // ============================================================================
  {
    partSku: 'AERO-VOLTEX-CYBER-01',
    category: 'AERO_BODYWORK',
    brandName: 'Voltex Racing Japan',
    partName: 'Voltex Cyber Evo Type-5 Carbon Fiber Swan-Neck GT Wing (1800mm)',
    priceCredits: 6200,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: 4.5,
    lateralGForceDelta: 0.35,
    brakingDistanceDeltaM: -2.0,
    durabilityRatingPct: 96.0,
    installationLaborHours: 3.0,
    description: 'Autoclave prepreg carbon fiber dual-element rear wing generating 450kg of downforce at 200 km/h with 15-way pitch adjustability.',
  },
  {
    partSku: 'AERO-APR-SPLITTER-02',
    category: 'AERO_BODYWORK',
    brandName: 'APR Performance',
    partName: 'APR Carbon Fiber Front Wind Splitter with Chassis Support Rods',
    priceCredits: 2100,
    tierRequirement: 'STREET_TIER_1',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: 3.2,
    lateralGForceDelta: 0.18,
    brakingDistanceDeltaM: -1.0,
    durabilityRatingPct: 94.0,
    installationLaborHours: 2.5,
    description: 'High-pressure autoclave molded carbon splitter with integrated air dam creating low-pressure ground effect under the front bumper.',
  },
  {
    partSku: 'AERO-ROCKETBUNNY-WB-03',
    category: 'AERO_BODYWORK',
    brandName: 'Pandem / Rocket Bunny',
    partName: 'Pandem Widebody Aerodynamic Kit (+75mm Overfenders)',
    priceCredits: 8900,
    tierRequirement: 'SPORT_TIER_2',
    compatibleEngineTypes: ['INLINE_4', 'INLINE_6', 'V6_TWINTURBO', 'V8_SUPERCHARGED', 'BOXER_6'],
    horsepowerGainHp: 0,
    torqueGainNm: 0,
    weightDeltaKg: 6.0,
    lateralGForceDelta: 0.22,
    brakingDistanceDeltaM: 0.0,
    durabilityRatingPct: 98.0,
    installationLaborHours: 16.0,
    description: 'Tra-Kyoto Kei Miura widebody conversion allowing 345-wide rear slick tires and dramatically wider track width.',
  },
];
