/**
 * ============================================================================
 * REALDRIVE SEED DATA - COMPREHENSIVE PARTS CATALOG (CARBON BUCKET SEATS & BEADLOCK FORGED RIMS)
 * ============================================================================
 */

import { PerformanceUpgradePart } from './HighPerformancePartsRegistryFull';

export const COMPREHENSIVE_PARTS_INT_DATABASE: readonly PerformanceUpgradePart[] = [
  {
    partSku: 'SKU_INT_UPGRADE_1',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 1',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 1440,
    massDeltaKg: 1.4,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_2',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 2',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 1680,
    massDeltaKg: 1.6,
    horsepowerDeltaHp: 23,
    torqueDeltaNm: 30,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_3',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 3',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 1920,
    massDeltaKg: -3.7,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_4',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 4',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 2160,
    massDeltaKg: 2,
    horsepowerDeltaHp: 31,
    torqueDeltaNm: 40,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_5',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 5',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 2400,
    massDeltaKg: 2.2,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_6',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 6',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 2640,
    massDeltaKg: -4.9,
    horsepowerDeltaHp: 39,
    torqueDeltaNm: 50,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_7',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 7',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 2880,
    massDeltaKg: 2.6,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_8',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 8',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 3120,
    massDeltaKg: 2.8,
    horsepowerDeltaHp: 47,
    torqueDeltaNm: 60,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_9',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 9',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 3360,
    massDeltaKg: -6.1,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_10',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 10',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 3600,
    massDeltaKg: 3.2,
    horsepowerDeltaHp: 55,
    torqueDeltaNm: 70,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_11',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 11',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 3840,
    massDeltaKg: 3.4,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_12',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 12',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 4080,
    massDeltaKg: -7.3,
    horsepowerDeltaHp: 63,
    torqueDeltaNm: 80,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_13',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 13',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 4320,
    massDeltaKg: 3.8,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_14',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 14',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 4560,
    massDeltaKg: 4,
    horsepowerDeltaHp: 71,
    torqueDeltaNm: 90,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_15',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 15',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 4800,
    massDeltaKg: -8.5,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_16',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 16',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 5040,
    massDeltaKg: 4.4,
    horsepowerDeltaHp: 79,
    torqueDeltaNm: 100,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_17',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 17',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 5280,
    massDeltaKg: 4.6,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_18',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 18',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 5520,
    massDeltaKg: -9.7,
    horsepowerDeltaHp: 87,
    torqueDeltaNm: 110,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_19',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 19',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 5760,
    massDeltaKg: 5,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_20',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 20',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 6000,
    massDeltaKg: 5.2,
    horsepowerDeltaHp: 95,
    torqueDeltaNm: 120,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_21',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 21',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 6240,
    massDeltaKg: -10.9,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_22',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 22',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 6480,
    massDeltaKg: 5.6,
    horsepowerDeltaHp: 103,
    torqueDeltaNm: 130,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_23',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 23',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 6720,
    massDeltaKg: 5.8,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_24',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 24',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 6960,
    massDeltaKg: -12.1,
    horsepowerDeltaHp: 111,
    torqueDeltaNm: 140,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_25',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 25',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 7200,
    massDeltaKg: 6.2,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_26',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 26',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 7440,
    massDeltaKg: 6.4,
    horsepowerDeltaHp: 119,
    torqueDeltaNm: 150,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_27',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 27',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 7680,
    massDeltaKg: -13.3,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_28',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 28',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 7920,
    massDeltaKg: 6.8,
    horsepowerDeltaHp: 127,
    torqueDeltaNm: 160,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_29',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 29',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 8160,
    massDeltaKg: 7,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_30',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 30',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 8400,
    massDeltaKg: -14.5,
    horsepowerDeltaHp: 135,
    torqueDeltaNm: 170,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_31',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 31',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 8640,
    massDeltaKg: 7.4,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_32',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 32',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 8880,
    massDeltaKg: 7.6,
    horsepowerDeltaHp: 143,
    torqueDeltaNm: 180,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_33',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 33',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 9120,
    massDeltaKg: -15.7,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_34',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 34',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 9360,
    massDeltaKg: 8,
    horsepowerDeltaHp: 151,
    torqueDeltaNm: 190,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_35',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 35',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 9600,
    massDeltaKg: 8.2,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_36',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 36',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 9840,
    massDeltaKg: -16.9,
    horsepowerDeltaHp: 159,
    torqueDeltaNm: 200,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_37',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 37',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 10080,
    massDeltaKg: 8.6,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_38',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 38',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 10320,
    massDeltaKg: 8.8,
    horsepowerDeltaHp: 167,
    torqueDeltaNm: 210,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_39',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 39',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 10560,
    massDeltaKg: -18.1,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_40',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 40',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 10800,
    massDeltaKg: 9.2,
    horsepowerDeltaHp: 175,
    torqueDeltaNm: 220,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_41',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 41',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 11040,
    massDeltaKg: 9.4,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_42',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 42',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 11280,
    massDeltaKg: -19.3,
    horsepowerDeltaHp: 183,
    torqueDeltaNm: 230,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_43',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 43',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 11520,
    massDeltaKg: 9.8,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_44',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 44',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 11760,
    massDeltaKg: 10,
    horsepowerDeltaHp: 191,
    torqueDeltaNm: 240,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_45',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 45',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 12000,
    massDeltaKg: -20.5,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_46',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 46',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 12240,
    massDeltaKg: 10.4,
    horsepowerDeltaHp: 199,
    torqueDeltaNm: 250,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_47',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 47',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 12480,
    massDeltaKg: 10.6,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_48',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 48',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 12720,
    massDeltaKg: -21.7,
    horsepowerDeltaHp: 207,
    torqueDeltaNm: 260,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_49',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 49',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 12960,
    massDeltaKg: 11,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_50',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 50',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 13200,
    massDeltaKg: 11.2,
    horsepowerDeltaHp: 215,
    torqueDeltaNm: 270,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_51',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 51',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 13440,
    massDeltaKg: -22.9,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_52',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 52',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 13680,
    massDeltaKg: 11.6,
    horsepowerDeltaHp: 223,
    torqueDeltaNm: 280,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_53',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 53',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 13920,
    massDeltaKg: 11.8,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_54',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 54',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 14160,
    massDeltaKg: -24.1,
    horsepowerDeltaHp: 231,
    torqueDeltaNm: 290,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_55',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 55',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 14400,
    massDeltaKg: 12.2,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_56',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 56',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 14640,
    massDeltaKg: 12.4,
    horsepowerDeltaHp: 239,
    torqueDeltaNm: 300,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_57',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 57',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 14880,
    massDeltaKg: -25.3,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_58',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 58',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 15120,
    massDeltaKg: 12.8,
    horsepowerDeltaHp: 247,
    torqueDeltaNm: 310,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_59',
    category: 'interior_weight_reduction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 59',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 15360,
    massDeltaKg: 13,
    horsepowerDeltaHp: 0,
    torqueDeltaNm: 0,
    topRpmIncreaseRpm: 0,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
  {
    partSku: 'SKU_INT_UPGRADE_60',
    category: 'forced_induction',
    brandName: 'RealDrive Pro Tuning Lab',
    partName: 'Carbon Bucket Seats & Beadlock Forged Rims Spec 60',
    description: 'High performance motorsport component homologated for competition series.',
    priceUSD: 15600,
    massDeltaKg: -26.5,
    horsepowerDeltaHp: 255,
    torqueDeltaNm: 320,
    topRpmIncreaseRpm: 400,
    brakeTorqueMultiplier: 1.0,
    aeroDownforceDeltaN: 0,
    aeroDragDeltaCd: 0,
    coolingEfficiencyBoostPercent: 0,
    durabilityFactor: 1.45,
    installationHours: 3.5,
    compatibilityVehicleClasses: ['hypercar', 'supercar', 'gt3_spec', 'sports_coupe']
  },
];

export class ComprehensivePartsINTService {
  public static getAllParts(): readonly PerformanceUpgradePart[] {
    return COMPREHENSIVE_PARTS_INT_DATABASE;
  }
}
