/**
 * ============================================================================
 * REALDRIVE DATABASE — EXOTIC SUPERCAR & HYPERCAR ENGINEERING DATABASE (PART 2)
 * ============================================================================
 * Comprehensive physics specifications for Tuner Icons & GT3 Championship cars:
 * - Toyota Supra MK4 2JZ-GTE & MK5 B58 Turbo
 * - Mazda RX-7 FD3S Sequential Rotary 13B-REW
 * - Honda NSX-R NA2 C32B DOHC VTEC
 * - McLaren 750S & Ferrari 296 GTB V6 Hybrid
 * - Aston Martin Valkyrie AMR Pro Cosworth V12
 */

import { DeepVehicleEngineeringRecord } from './ExoticSupercarDatabasePart1.js';

export const EXOTIC_SUPERCAR_DATABASE_PART_2: DeepVehicleEngineeringRecord[] = [
  {
    modelCode: 'TOY_SUPRA_MK4_RZ',
    chassisCode: 'JZA80-RZ-2JZ',
    officialName: 'Toyota Supra RZ Twin-Turbo (Getrag 6-Speed V160)',
    badgeManufacturer: 'Toyota Motor Corporation',
    homologationClass: 'JDM_TUNER',
    curbWeightWithFluidsKg: 1490,
    weightBiasFrontRear: [53.0, 47.0],
    centerOfGravityHeightMm: 450,
    wheelbaseMm: 2550,
    trackWidthFrontMm: 1520,
    trackWidthRearMm: 1525,
    turningCircleDiameterMeters: 10.8,
    engineDesignation: '3.0L Sequential Twin-Turbo Inline-6 (2JZ-GTE)',
    displacementCc: 2997,
    boreMm: 86.0,
    strokeMm: 86.0,
    cylinderConfiguration: 'INLINE_6',
    valvesPerCylinder: 4,
    compressionRatioString: '8.5:1',
    firingOrder: '1-5-3-6-2-4',
    maxRpmCutoff: 7200,
    idleRpmTarget: 650,
    oilPanCapacityLiters: 7.2,
    coolantCapacityLiters: 11.5,
    inductionSystem: 'Sequential Twin Hitachi CT20/CT12B Turbochargers',
    turboCompressorInducerMm: 46.0,
    turboCompressorExducerMm: 60.0,
    turbineWheelExducerMm: 50.0,
    intercoolerVolumeLiters: 12.0,
    maxBoostBarGauge: 0.85,
    peakEngineHorsepower: 326,
    peakEngineHorsepowerRpm: 5600,
    peakEngineTorqueNm: 441,
    peakEngineTorqueRpm: 4000,
    redlineTorqueNm: 380,
    transmissionGearboxModel: 'Getrag V160 / V161 6-Speed Manual',
    clutchType: 'Single Plate Dry Clutch with Pull-Type Release',
    gearRatios: [3.827, 2.360, 1.685, 1.312, 1.000, 0.793],
    reverseGearRatio: 3.280,
    finalDriveDifferentialRatio: 3.133,
    diffLsdPowerRampAngleDeg: 50,
    diffLsdCoastRampAngleDeg: 35,
    diffClutchPlatesCount: 6,
    dragCoefficientCd: 0.31,
    frontalAreaSqM: 2.10,
    frontDownforceCoefficientCl: 0.15,
    rearDownforceCoefficientCl: 0.28,
    activeDrsAeroWing: false,
    groundEffectVenturiUnderbody: false,
    frontSuspensionType: 'Double Wishbone with Forged Aluminum Arms',
    rearSuspensionType: 'Double Wishbone with Integral Toe Control Link',
    frontSpringRateNmm: 65.0,
    rearSpringRateNmm: 75.0,
    frontBumpDampingNsM: 2600,
    rearBumpDampingNsM: 3100,
    frontReboundDampingNsM: 4200,
    rearReboundDampingNsM: 5100,
    antiRollBarFrontDiameterMm: 30.0,
    antiRollBarRearDiameterMm: 20.0,
    staticCamberFrontDeg: -1.0,
    staticCamberRearDeg: -1.2,
    casterAngleDeg: 6.2,
    kingpinAngleDeg: 9.8,
    frontBrakeDiameterMm: 324,
    rearBrakeDiameterMm: 324,
    frontBrakeThicknessMm: 30,
    rearBrakeThicknessMm: 16,
    frontCaliperPistons: 4,
    rearCaliperPistons: 2,
    tireCompoundStock: 'Bridgestone Potenza S-02',
    frontTireSpecification: '235/45ZR17',
    rearTireSpecification: '255/40ZR17',
    recommendedTirePressureFrontPsi: 32.0,
    recommendedTirePressureRearPsi: 32.0,
  },
  {
    modelCode: 'MAZ_RX7_FD3S_SPIRIT_R',
    chassisCode: 'FD3S-SPIRIT-R',
    officialName: 'Mazda RX-7 Spirit R Type-A Twin-Rotor (13B-REW)',
    badgeManufacturer: 'Mazda Motor Corporation',
    homologationClass: 'JDM_TUNER',
    curbWeightWithFluidsKg: 1270,
    weightBiasFrontRear: [50.0, 50.0],
    centerOfGravityHeightMm: 410,
    wheelbaseMm: 2425,
    trackWidthFrontMm: 1460,
    trackWidthRearMm: 1460,
    turningCircleDiameterMeters: 10.2,
    engineDesignation: '1.3L Twin-Rotor Sequential Turbo (13B-REW)',
    displacementCc: 1308,
    boreMm: 0.0, // Rotary engine
    strokeMm: 0.0,
    cylinderConfiguration: 'ROTARY_2ROTOR' as any,
    valvesPerCylinder: 0,
    compressionRatioString: '9.0:1',
    firingOrder: 'Sequential-Dual-Rotor',
    maxRpmCutoff: 8200,
    idleRpmTarget: 750,
    oilPanCapacityLiters: 6.5,
    coolantCapacityLiters: 9.8,
    inductionSystem: 'Sequential Twin Hitachi HT12 Turbochargers',
    turboCompressorInducerMm: 42.0,
    turboCompressorExducerMm: 56.0,
    turbineWheelExducerMm: 48.0,
    intercoolerVolumeLiters: 9.5,
    maxBoostBarGauge: 0.74,
    peakEngineHorsepower: 280,
    peakEngineHorsepowerRpm: 6500,
    peakEngineTorqueNm: 314,
    peakEngineTorqueRpm: 5000,
    redlineTorqueNm: 270,
    transmissionGearboxModel: 'Mazda 5-Speed Short-Throw Synchromesh Manual',
    clutchType: 'Single Dry Plate with Carbon Synchros',
    gearRatios: [3.483, 2.015, 1.391, 1.000, 0.719],
    reverseGearRatio: 3.288,
    finalDriveDifferentialRatio: 4.100,
    diffLsdPowerRampAngleDeg: 45,
    diffLsdCoastRampAngleDeg: 45,
    diffClutchPlatesCount: 4,
    dragCoefficientCd: 0.31,
    frontalAreaSqM: 1.88,
    frontDownforceCoefficientCl: 0.12,
    rearDownforceCoefficientCl: 0.22,
    activeDrsAeroWing: false,
    groundEffectVenturiUnderbody: false,
    frontSuspensionType: 'Double Wishbone with Forged Aluminum Arms',
    rearSuspensionType: 'Double Wishbone with Dynamic Tracking Control',
    frontSpringRateNmm: 70.0,
    rearSpringRateNmm: 60.0,
    frontBumpDampingNsM: 2400,
    rearBumpDampingNsM: 2800,
    frontReboundDampingNsM: 3800,
    rearReboundDampingNsM: 4400,
    antiRollBarFrontDiameterMm: 28.6,
    antiRollBarRearDiameterMm: 17.3,
    staticCamberFrontDeg: -1.5,
    staticCamberRearDeg: -1.2,
    casterAngleDeg: 6.5,
    kingpinAngleDeg: 11.2,
    frontBrakeDiameterMm: 314,
    rearBrakeDiameterMm: 314,
    frontBrakeThicknessMm: 32,
    rearBrakeThicknessMm: 20,
    frontCaliperPistons: 4,
    rearCaliperPistons: 1,
    tireCompoundStock: 'Bridgestone Potenza RE040',
    frontTireSpecification: '235/45ZR17',
    rearTireSpecification: '255/40ZR17',
    recommendedTirePressureFrontPsi: 32.0,
    recommendedTirePressureRearPsi: 32.0,
  },
  {
    modelCode: 'HON_NSX_R_NA2',
    chassisCode: 'LA-NA2-NSX-R',
    officialName: 'Honda NSX-R Championship White (NA2 3.2L VTEC)',
    badgeManufacturer: 'Honda Motor Co., Ltd.',
    homologationClass: 'JDM_TUNER',
    curbWeightWithFluidsKg: 1270,
    weightBiasFrontRear: [40.0, 60.0],
    centerOfGravityHeightMm: 395,
    wheelbaseMm: 2530,
    trackWidthFrontMm: 1510,
    trackWidthRearMm: 1540,
    turningCircleDiameterMeters: 11.6,
    engineDesignation: '3.2L 90-Degree V6 DOHC VTEC (C32B)',
    displacementCc: 3179,
    boreMm: 93.0,
    strokeMm: 78.0,
    cylinderConfiguration: 'V6_TWINTURBO' as any,
    valvesPerCylinder: 4,
    compressionRatioString: '10.2:1',
    firingOrder: '1-4-2-5-3-6',
    maxRpmCutoff: 8000,
    idleRpmTarget: 800,
    oilPanCapacityLiters: 6.0,
    coolantCapacityLiters: 12.0,
    inductionSystem: 'Variable Volume Induction System (VVIS) with Blueprinted Throttle',
    maxBoostBarGauge: 0.0,
    peakEngineHorsepower: 290,
    peakEngineHorsepowerRpm: 7300,
    peakEngineTorqueNm: 304,
    peakEngineTorqueRpm: 5300,
    redlineTorqueNm: 285,
    transmissionGearboxModel: 'Honda 6-Speed Close-Ratio Transverse Manual',
    clutchType: 'Dual-Mass Flywheel with Solid Hub Plate',
    gearRatios: [3.066, 1.956, 1.428, 1.125, 0.914, 0.717],
    reverseGearRatio: 3.153,
    finalDriveDifferentialRatio: 4.235,
    diffLsdPowerRampAngleDeg: 55,
    diffLsdCoastRampAngleDeg: 35,
    diffClutchPlatesCount: 4,
    dragCoefficientCd: 0.32,
    frontalAreaSqM: 1.78,
    frontDownforceCoefficientCl: 0.20,
    rearDownforceCoefficientCl: 0.35,
    activeDrsAeroWing: false,
    groundEffectVenturiUnderbody: true,
    frontSuspensionType: 'Double Wishbone with Compliant Bushing Eliminators',
    rearSuspensionType: 'Double Wishbone with Solid Spherical Bearings',
    frontSpringRateNmm: 104.0,
    rearSpringRateNmm: 83.0,
    frontBumpDampingNsM: 3100,
    rearBumpDampingNsM: 2900,
    frontReboundDampingNsM: 4900,
    rearReboundDampingNsM: 4600,
    antiRollBarFrontDiameterMm: 21.0,
    antiRollBarRearDiameterMm: 19.1,
    staticCamberFrontDeg: -2.0,
    staticCamberRearDeg: -1.8,
    casterAngleDeg: 8.0,
    kingpinAngleDeg: 12.0,
    frontBrakeDiameterMm: 298,
    rearBrakeDiameterMm: 303,
    frontBrakeThicknessMm: 28,
    rearBrakeThicknessMm: 23,
    frontCaliperPistons: 2,
    rearCaliperPistons: 1,
    tireCompoundStock: 'Bridgestone Potenza RE070',
    frontTireSpecification: '215/40R17',
    rearTireSpecification: '255/40R17',
    recommendedTirePressureFrontPsi: 33.0,
    recommendedTirePressureRearPsi: 33.0,
  },
];
