/**
 * ============================================================================
 * REALDRIVE DATABASE SEED DATA — COMPREHENSIVE 100-VEHICLE CATALOG DATASET
 * ============================================================================
 * Full engineering specifications for 100 unique vehicle models across 10 classes:
 * 1. Supercars (Ferrari, Lamborghini, McLaren, Porsche, Ford GT, Corvette)
 * 2. Hypercars (Bugatti, Koenigsegg, Pagani, Rimac, Aston Martin Valkyrie)
 * 3. Track GT3 & Cup Cars (Porsche 911 GT3 R, AMG GT3, M4 GT3, Huracán GT3 EVO2)
 * 4. Formula Monoposto Single-Seater (Formula 1, Super Formula, Formula E)
 * 5. JDM Tuner Classics (Skyline GT-R, Supra MK4/MK5, RX-7 FD, NSX Type R, Lancer EVO, WRX STI)
 * 6. American Muscle (Mustang Shelby GT500, Dodge Challenger Hellcat, Camaro ZL1, Viper ACR)
 * 7. European Luxury Performance (BMW M5 CS, Mercedes-AMG E63 S, Audi RS6 Avant, Panamera Turbo)
 * 8. Electric Hyper & Performance EV (Rimac Nevera, Tesla Model S Plaid, Porsche Taycan Turbo S)
 * 9. Off-Road 4x4 Trophy Trucks & Rally (Ford Raptor R, RAM TRX, Lancer WRC, Toyota Hilux Dakar)
 * 10. Commercial Heavy Logistics (Kenworth W900, Peterbilt 389, Mercedes Actros, Scania R730)
 */

import { VehicleEntity } from '../entities/VehicleEntity.js';

export interface VehicleCatalogItem {
  modelId: string;
  name: string;
  brand: string;
  vehicleClass: VehicleEntity['vehicleClass'];
  year: number;
  basePrice: number;
  marketValuation: number;
  engineType: VehicleEntity['engineType'];
  drivetrain: VehicleEntity['drivetrain'];
  transmissionType: VehicleEntity['transmissionType'];
  horsepower: number;
  torqueNm: number;
  curbWeightKg: number;
  topSpeedKmh: number;
  zeroToHundredSec: number;
  brakingDistance100To0M: number;
  lateralGForce: number;
  fuelCapacityLiters: number;
  paintColor: string;
  paintFinish: VehicleEntity['paintFinish'];
  description: string;
}

export const VEHICLE_CATALOG_100: VehicleCatalogItem[] = [
  // ==========================================
  // 1. HYPERCARS (10 Cars)
  // ==========================================
  {
    modelId: 'bugatti_chiron_supersport',
    name: 'Molsheim SS 300+ Hypercar',
    brand: 'Molsheim Hypercars',
    vehicleClass: 'HYPERCAR',
    year: 2024,
    basePrice: 3800000,
    marketValuation: 4100000,
    engineType: 'V12_QUADTURBO',
    drivetrain: 'AWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 1600,
    torqueNm: 1600,
    curbWeightKg: 1975,
    topSpeedKmh: 440,
    zeroToHundredSec: 2.3,
    brakingDistance100To0M: 31.0,
    lateralGForce: 1.40,
    fuelCapacityLiters: 100,
    paintColor: '#0f172a',
    paintFinish: 'FORGED_CARBON' as any,
    description: 'The 300+ MPH world record breaking hypercar powered by an 8.0L Quad-Turbo W16 powerplant.',
  },
  {
    modelId: 'koenigsegg_jesko_absolut',
    name: 'Angelholm Jesko Absolut Phantom',
    brand: 'Angelholm Engineering',
    vehicleClass: 'HYPERCAR',
    year: 2024,
    basePrice: 3400000,
    marketValuation: 3900000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 1625,
    torqueNm: 1500,
    curbWeightKg: 1390,
    topSpeedKmh: 480,
    zeroToHundredSec: 2.4,
    brakingDistance100To0M: 29.5,
    lateralGForce: 1.60,
    fuelCapacityLiters: 72,
    paintColor: '#ffffff',
    paintFinish: 'METALLIC',
    description: 'Ultra low-drag aerodynamic silhouette with 9-speed Light Speed Transmission and flat-plane V8 twin-turbo.',
  },
  {
    modelId: 'pagani_utopia_coupe',
    name: 'Modena Utopia V12 Artisan',
    brand: 'Modena Automobili',
    vehicleClass: 'HYPERCAR',
    year: 2024,
    basePrice: 2900000,
    marketValuation: 3200000,
    engineType: 'V12_QUADTURBO',
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 864,
    torqueNm: 1100,
    curbWeightKg: 1280,
    topSpeedKmh: 370,
    zeroToHundredSec: 2.9,
    brakingDistance100To0M: 28.0,
    lateralGForce: 1.50,
    fuelCapacityLiters: 80,
    paintColor: '#64748b',
    paintFinish: 'SATIN_PEARL',
    description: 'Pure analog driving perfection featuring handcrafted Carbo-Titanium monocoque and gated manual shifter.',
  },
  {
    modelId: 'rimac_nevera_time_attack',
    name: 'Sveta Nevera Quad-Motor EV',
    brand: 'Rimac Technology',
    vehicleClass: 'ELECTRIC_HYPER',
    year: 2024,
    basePrice: 2500000,
    marketValuation: 2800000,
    engineType: 'DUAL_MOTOR_EV',
    drivetrain: 'AWD',
    transmissionType: 'SINGLE_DIRECT_EV',
    horsepower: 1914,
    torqueNm: 2360,
    curbWeightKg: 2150,
    topSpeedKmh: 412,
    zeroToHundredSec: 1.81,
    brakingDistance100To0M: 28.5,
    lateralGForce: 1.45,
    fuelCapacityLiters: 0,
    paintColor: '#06b6d4',
    paintFinish: 'GLOSS',
    description: 'Quad-motor individual torque vectoring EV generating 1,914 horsepower with 1.81s 0-100 km/h acceleration.',
  },
  {
    modelId: 'aston_valkyrie_amr_pro',
    name: 'Gaydon Valkyrie AMR Track Weapon',
    brand: 'Gaydon Performance',
    vehicleClass: 'HYPERCAR',
    year: 2024,
    basePrice: 3500000,
    marketValuation: 4200000,
    engineType: 'V12_QUADTURBO',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 1160,
    torqueNm: 900,
    curbWeightKg: 1000,
    topSpeedKmh: 365,
    zeroToHundredSec: 2.2,
    brakingDistance100To0M: 25.0,
    lateralGForce: 3.30,
    fuelCapacityLiters: 65,
    paintColor: '#84cc16',
    paintFinish: 'HIGH_GLOSS' as any,
    description: 'Formula 1 aerodynamics with 11,100 RPM naturally aspirated Cosworth 6.5L V12 and 3.3G cornering force.',
  },
  {
    modelId: 'mclaren_w1_hybrid',
    name: 'Woking W1 Ultimate Series',
    brand: 'Woking Supercars',
    vehicleClass: 'HYPERCAR',
    year: 2025,
    basePrice: 2100000,
    marketValuation: 2600000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 1275,
    torqueNm: 1340,
    curbWeightKg: 1399,
    topSpeedKmh: 350,
    zeroToHundredSec: 2.7,
    brakingDistance100To0M: 26.5,
    lateralGForce: 1.75,
    fuelCapacityLiters: 68,
    paintColor: '#f97316',
    paintFinish: 'METALLIC',
    description: 'Ground-effect active aero Longtail wing producing 1,000kg downforce with twin-turbo hybrid V8.',
  },
  {
    modelId: 'ferrari_f80_concept',
    name: 'Maranello F80 Hyper V6 Twin-Turbo',
    brand: 'Maranello Scuderia',
    vehicleClass: 'HYPERCAR',
    year: 2025,
    basePrice: 3900000,
    marketValuation: 4500000,
    engineType: 'V6_TWINTURBO',
    drivetrain: 'AWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 1200,
    torqueNm: 1150,
    curbWeightKg: 1525,
    topSpeedKmh: 350,
    zeroToHundredSec: 2.15,
    brakingDistance100To0M: 26.0,
    lateralGForce: 1.80,
    fuelCapacityLiters: 65,
    paintColor: '#dc2626',
    paintFinish: 'GLOSS',
    description: 'Le Mans Hypercar winning 120-degree 3.0L V6 with electric turbos and active suspension dampers.',
  },
  {
    modelId: 'mercedes_amg_one',
    name: 'Affalterbach ONE F1 Hypercar',
    brand: 'Affalterbach Performance',
    vehicleClass: 'HYPERCAR',
    year: 2024,
    basePrice: 2750000,
    marketValuation: 3300000,
    engineType: 'V6_TWINTURBO',
    drivetrain: 'AWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 1063,
    torqueNm: 1000,
    curbWeightKg: 1695,
    topSpeedKmh: 352,
    zeroToHundredSec: 2.9,
    brakingDistance100To0M: 27.0,
    lateralGForce: 1.70,
    fuelCapacityLiters: 55,
    paintColor: '#94a3b8',
    paintFinish: 'METALLIC',
    description: 'Authentic 1.6L Formula 1 turbocharged V6 revving to 11,000 RPM with MGU-K and MGU-H hybrid recovery.',
  },
  {
    modelId: 'hennessey_venom_f5',
    name: 'Texas Venom F5 Twin Turbo V8',
    brand: 'American Fury',
    vehicleClass: 'HYPERCAR',
    year: 2024,
    basePrice: 2100000,
    marketValuation: 2400000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 1817,
    torqueNm: 1617,
    curbWeightKg: 1360,
    topSpeedKmh: 485,
    zeroToHundredSec: 2.6,
    brakingDistance100To0M: 30.0,
    lateralGForce: 1.40,
    fuelCapacityLiters: 90,
    paintColor: '#eab308',
    paintFinish: 'HIGH_GLOSS' as any,
    description: '6.6L twin-turbo Fury V8 producing 1,817 HP with a bespoke carbon fiber tub designed for 500 km/h.',
  },
  {
    modelId: 'de_tomaso_p72',
    name: 'Modena P72 Sculpted V8',
    brand: 'Modena Automobili',
    vehicleClass: 'HYPERCAR',
    year: 2024,
    basePrice: 1600000,
    marketValuation: 1900000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 750,
    torqueNm: 900,
    curbWeightKg: 1350,
    topSpeedKmh: 340,
    zeroToHundredSec: 3.2,
    brakingDistance100To0M: 29.0,
    lateralGForce: 1.45,
    fuelCapacityLiters: 70,
    paintColor: '#b91c1c',
    paintFinish: 'METALLIC',
    description: '1960s endurance prototype aesthetics with exposed copper linkages and supercharged Coyote 5.0L V8.',
  },

  // ==========================================
  // 2. SUPERCARS (10 Cars)
  // ==========================================
  {
    modelId: 'ferrari_296_gtb',
    name: 'Maranello 296 Assetto Fiorano',
    brand: 'Maranello Scuderia',
    vehicleClass: 'SUPERCAR',
    year: 2024,
    basePrice: 340000,
    marketValuation: 390000,
    engineType: 'V6_TWINTURBO',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 830,
    torqueNm: 740,
    curbWeightKg: 1470,
    topSpeedKmh: 330,
    zeroToHundredSec: 2.9,
    brakingDistance100To0M: 28.5,
    lateralGForce: 1.45,
    fuelCapacityLiters: 65,
    paintColor: '#dc2626',
    paintFinish: 'GLOSS',
    description: '120-degree hot-V twin-turbo V6 hybrid with Assetto Fiorano track handling pack.',
  },
  {
    modelId: 'lamborghini_revuelto',
    name: 'SantAgata Revuelto V12 HPEV',
    brand: 'SantAgata Bulls',
    vehicleClass: 'SUPERCAR',
    year: 2024,
    basePrice: 600000,
    marketValuation: 720000,
    engineType: 'V12_QUADTURBO',
    drivetrain: 'AWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 1015,
    torqueNm: 1062,
    curbWeightKg: 1772,
    topSpeedKmh: 350,
    zeroToHundredSec: 2.5,
    brakingDistance100To0M: 29.0,
    lateralGForce: 1.50,
    fuelCapacityLiters: 75,
    paintColor: '#eab308',
    paintFinish: 'METALLIC',
    description: 'Naturally aspirated 6.5L V12 screaming to 9,500 RPM combined with 3 electric drive motors.',
  },
  {
    modelId: 'mclaren_750s_coupe',
    name: 'Woking 750S Superlight',
    brand: 'Woking Supercars',
    vehicleClass: 'SUPERCAR',
    year: 2024,
    basePrice: 330000,
    marketValuation: 360000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 750,
    torqueNm: 800,
    curbWeightKg: 1277,
    topSpeedKmh: 332,
    zeroToHundredSec: 2.8,
    brakingDistance100To0M: 28.0,
    lateralGForce: 1.55,
    fuelCapacityLiters: 72,
    paintColor: '#ea580c',
    paintFinish: 'GLOSS',
    description: 'Proactive Chassis Control III hydraulic suspension with twin-turbo 4.0L flat-plane V8.',
  },
  {
    modelId: 'porsche_911_turbo_s',
    name: 'Stuttgart 911 Turbo S 992',
    brand: 'Stuttgart Precision',
    vehicleClass: 'SUPERCAR',
    year: 2024,
    basePrice: 235000,
    marketValuation: 260000,
    engineType: 'BOXER_6',
    drivetrain: 'AWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 650,
    torqueNm: 800,
    curbWeightKg: 1640,
    topSpeedKmh: 330,
    zeroToHundredSec: 2.6,
    brakingDistance100To0M: 28.5,
    lateralGForce: 1.40,
    fuelCapacityLiters: 67,
    paintColor: '#475569',
    paintFinish: 'METALLIC',
    description: 'VTG variable turbine geometry 3.8L twin-turbo boxer with launch control catapult acceleration.',
  },
  {
    modelId: 'chevrolet_corvette_zr1_c8',
    name: 'Detroit Corvette C8 ZR1 Twin-Turbo',
    brand: 'American Muscle Co.',
    vehicleClass: 'SUPERCAR',
    year: 2025,
    basePrice: 175000,
    marketValuation: 210000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 1064,
    torqueNm: 1123,
    curbWeightKg: 1665,
    topSpeedKmh: 375,
    zeroToHundredSec: 2.5,
    brakingDistance100To0M: 28.0,
    lateralGForce: 1.55,
    fuelCapacityLiters: 70,
    paintColor: '#3b82f6',
    paintFinish: 'GLOSS',
    description: '5.5L LT7 flat-plane twin-turbo V8 with carbon fiber split rear window and active ZTK aero wing.',
  },
  {
    modelId: 'ford_gt_carbon_edition',
    name: 'Dearborn GT Carbon Edition',
    brand: 'Dearborn Heritage',
    vehicleClass: 'SUPERCAR',
    year: 2022,
    basePrice: 550000,
    marketValuation: 1200000,
    engineType: 'V6_TWINTURBO',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 660,
    torqueNm: 746,
    curbWeightKg: 1385,
    topSpeedKmh: 348,
    zeroToHundredSec: 3.0,
    brakingDistance100To0M: 28.0,
    lateralGForce: 1.60,
    fuelCapacityLiters: 58,
    paintColor: '#1e293b',
    paintFinish: 'METALLIC',
    description: 'Le Mans 24h GTE winning carbon fiber teardrop aerodynamics with torsion bar race suspension.',
  },
  {
    modelId: 'audi_r8_v10_performance',
    name: 'Ingolstadt R8 V10 GT RWD',
    brand: 'Ingolstadt Dynamics',
    vehicleClass: 'SUPERCAR',
    year: 2023,
    basePrice: 210000,
    marketValuation: 240000,
    engineType: 'V10_NATURAL',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 620,
    torqueNm: 580,
    curbWeightKg: 1570,
    topSpeedKmh: 320,
    zeroToHundredSec: 3.4,
    brakingDistance100To0M: 30.0,
    lateralGForce: 1.40,
    fuelCapacityLiters: 73,
    paintColor: '#6b7280',
    paintFinish: 'MATTE',
    description: '8,700 RPM naturally aspirated 5.2L V10 with Torque Rear drift mode switch.',
  },
  {
    modelId: 'maserati_mc20_cielo',
    name: 'Bologna MC20 Nettuno Twin-Turbo',
    brand: 'Bologna Trident',
    vehicleClass: 'SUPERCAR',
    year: 2024,
    basePrice: 240000,
    marketValuation: 270000,
    engineType: 'V6_TWINTURBO',
    drivetrain: 'RWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 630,
    torqueNm: 730,
    curbWeightKg: 1475,
    topSpeedKmh: 325,
    zeroToHundredSec: 2.9,
    brakingDistance100To0M: 29.5,
    lateralGForce: 1.45,
    fuelCapacityLiters: 60,
    paintColor: '#0284c7',
    paintFinish: 'GLOSS',
    description: 'Formula 1 pre-chamber combustion Nettuno 3.0L twin-turbo with carbon fiber monocoque.',
  },
  {
    modelId: 'nissan_gtr_nismo_2024',
    name: 'Godzilla GT-R R35 Nismo',
    brand: 'Apex Automotive',
    vehicleClass: 'JDM_TUNER',
    year: 2024,
    basePrice: 220000,
    marketValuation: 250000,
    engineType: 'V6_TWINTURBO',
    drivetrain: 'AWD',
    transmissionType: 'DCT_7SPD',
    horsepower: 600,
    torqueNm: 652,
    curbWeightKg: 1720,
    topSpeedKmh: 330,
    zeroToHundredSec: 2.7,
    brakingDistance100To0M: 30.0,
    lateralGForce: 1.35,
    fuelCapacityLiters: 74,
    paintColor: '#e11d48',
    paintFinish: 'METALLIC',
    description: 'ATTESA E-TS all-wheel drive with GT3 turbochargers and carbon ceramic Brembo brakes.',
  },
  {
    modelId: 'lexus_lfa_nurburgring',
    name: 'Aichi LFA Nürburgring Edition',
    brand: 'Aichi Motors',
    vehicleClass: 'SUPERCAR',
    year: 2012,
    basePrice: 450000,
    marketValuation: 1400000,
    engineType: 'V10_NATURAL',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 570,
    torqueNm: 480,
    curbWeightKg: 1480,
    topSpeedKmh: 325,
    zeroToHundredSec: 3.7,
    brakingDistance100To0M: 30.5,
    lateralGForce: 1.45,
    fuelCapacityLiters: 73,
    paintColor: '#f59e0b',
    paintFinish: 'HIGH_GLOSS' as any,
    description: 'Yamaha acoustic tuned 4.8L 1LR-GUE V10 revving from idle to 9,000 RPM in 0.6 seconds.',
  },

  // ==========================================
  // 3. TRACK GT3 & CUP CARS (10 Cars)
  // ==========================================
  {
    modelId: 'porsche_911_gt3_r_992',
    name: 'Stuttgart 911 GT3 R 992 FIA-GT3',
    brand: 'Stuttgart Precision',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 510000,
    marketValuation: 580000,
    engineType: 'BOXER_6',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 565,
    torqueNm: 530,
    curbWeightKg: 1250,
    topSpeedKmh: 295,
    zeroToHundredSec: 2.8,
    brakingDistance100To0M: 24.5,
    lateralGForce: 2.20,
    fuelCapacityLiters: 117,
    paintColor: '#10b981',
    paintFinish: 'GLOSS',
    description: 'FIA GT3 homologated 4.2L flat-six endurance racing machine with swan-neck rear wing.',
  },
  {
    modelId: 'mercedes_amg_gt3_evo',
    name: 'Affalterbach AMG GT3 EVO',
    brand: 'Affalterbach Performance',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 480000,
    marketValuation: 530000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 550,
    torqueNm: 650,
    curbWeightKg: 1285,
    topSpeedKmh: 290,
    zeroToHundredSec: 2.9,
    brakingDistance100To0M: 25.0,
    lateralGForce: 2.15,
    fuelCapacityLiters: 120,
    paintColor: '#64748b',
    paintFinish: 'MATTE',
    description: 'Thundering 6.2L naturally aspirated M159 V8 with drop-forged wishbone suspension.',
  },
  {
    modelId: 'bmw_m4_gt3',
    name: 'Bavaria M4 GT3 Competition',
    brand: 'Bavaria Motorsport',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 460000,
    marketValuation: 510000,
    engineType: 'INLINE_6',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 590,
    torqueNm: 700,
    curbWeightKg: 1260,
    topSpeedKmh: 298,
    zeroToHundredSec: 2.8,
    brakingDistance100To0M: 24.8,
    lateralGForce: 2.10,
    fuelCapacityLiters: 120,
    paintColor: '#3b82f6',
    paintFinish: 'GLOSS',
    description: 'P58 3.0L twin-turbo straight-six with Xtrac 6-speed sequential transaxle.',
  },
  {
    modelId: 'ferrari_296_gt3',
    name: 'Maranello 296 GT3 Competizione',
    brand: 'Maranello Scuderia',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 530000,
    marketValuation: 600000,
    engineType: 'V6_TWINTURBO',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 600,
    torqueNm: 710,
    curbWeightKg: 1250,
    topSpeedKmh: 305,
    zeroToHundredSec: 2.7,
    brakingDistance100To0M: 24.0,
    lateralGForce: 2.25,
    fuelCapacityLiters: 120,
    paintColor: '#dc2626',
    paintFinish: 'GLOSS',
    description: '24 Hours of Nürburgring winner with modular carbon subframes for rapid 2-minute pit repairs.',
  },
  {
    modelId: 'lamborghini_huracan_gt3_evo2',
    name: 'SantAgata Huracan GT3 EVO2',
    brand: 'SantAgata Bulls',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 490000,
    marketValuation: 540000,
    engineType: 'V10_NATURAL',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 580,
    torqueNm: 550,
    curbWeightKg: 1230,
    topSpeedKmh: 295,
    zeroToHundredSec: 2.8,
    brakingDistance100To0M: 24.5,
    lateralGForce: 2.20,
    fuelCapacityLiters: 120,
    paintColor: '#eab308',
    paintFinish: 'GLOSS',
    description: 'Roof scoop snorkel induction feeding individual throttle bodies on the 5.2L V10.',
  },
  {
    modelId: 'corvette_z06_gt3_r',
    name: 'Detroit Corvette Z06 GT3.R',
    brand: 'American Muscle Co.',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 470000,
    marketValuation: 520000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 550,
    torqueNm: 620,
    curbWeightKg: 1270,
    topSpeedKmh: 292,
    zeroToHundredSec: 2.9,
    brakingDistance100To0M: 25.2,
    lateralGForce: 2.15,
    fuelCapacityLiters: 120,
    paintColor: '#facc15',
    paintFinish: 'GLOSS',
    description: '5.5L flat-plane crank LT6.R with titanium intake valves and Pratt Miller chassis setup.',
  },
  {
    modelId: 'ford_mustang_gt3',
    name: 'Dearborn Mustang Dark Horse GT3',
    brand: 'Dearborn Heritage',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 450000,
    marketValuation: 500000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 550,
    torqueNm: 640,
    curbWeightKg: 1290,
    topSpeedKmh: 290,
    zeroToHundredSec: 2.9,
    brakingDistance100To0M: 25.5,
    lateralGForce: 2.10,
    fuelCapacityLiters: 120,
    paintColor: '#1e3a8a',
    paintFinish: 'MATTE',
    description: '5.4L Coyote-derived naturally aspirated V8 built by M-Sport with carbon widebody aero.',
  },
  {
    modelId: 'mclaren_720s_gt3_evo',
    name: 'Woking 720S GT3 EVO',
    brand: 'Woking Supercars',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 520000,
    marketValuation: 570000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 570,
    torqueNm: 680,
    curbWeightKg: 1225,
    topSpeedKmh: 300,
    zeroToHundredSec: 2.7,
    brakingDistance100To0M: 24.2,
    lateralGForce: 2.22,
    fuelCapacityLiters: 120,
    paintColor: '#f97316',
    paintFinish: 'GLOSS',
    description: 'Ultra-stiff MonoCage II-S carbon tub with Öhlins TTX40 4-way through-rod dampers.',
  },
  {
    modelId: 'aston_vantage_gt3_evo',
    name: 'Gaydon Vantage GT3 EVO',
    brand: 'Gaydon Performance',
    vehicleClass: 'TRACK_GT3',
    year: 2024,
    basePrice: 475000,
    marketValuation: 525000,
    engineType: 'V8_SUPERCHARGED',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 545,
    torqueNm: 700,
    curbWeightKg: 1275,
    topSpeedKmh: 294,
    zeroToHundredSec: 2.8,
    brakingDistance100To0M: 25.0,
    lateralGForce: 2.12,
    fuelCapacityLiters: 120,
    paintColor: '#059669',
    paintFinish: 'GLOSS',
    description: '4.0L twin-turbo V8 endurance racer featuring revised nose aero and high-downforce louvers.',
  },
  {
    modelId: 'audi_r8_lms_gt3_evo_ii',
    name: 'Ingolstadt R8 LMS GT3 EVO II',
    brand: 'Ingolstadt Dynamics',
    vehicleClass: 'TRACK_GT3',
    year: 2023,
    basePrice: 465000,
    marketValuation: 515000,
    engineType: 'V10_NATURAL',
    drivetrain: 'RWD',
    transmissionType: 'SEQUENTIAL_6SPD',
    horsepower: 585,
    torqueNm: 550,
    curbWeightKg: 1225,
    topSpeedKmh: 300,
    zeroToHundredSec: 2.8,
    brakingDistance100To0M: 24.5,
    lateralGForce: 2.18,
    fuelCapacityLiters: 120,
    paintColor: '#e11d48',
    paintFinish: 'GLOSS',
    description: 'Suspension setup with 4-way adjustable dampers and roof-mounted high-flow air intake.',
  },

  // ==========================================
  // 4. JDM TUNER & DRIFT ICONS (10 Cars)
  // ==========================================
  {
    modelId: 'toyota_supra_mk4_turbo',
    name: 'Toyota Supra RZ 2JZ-GTE Twin-Turbo',
    brand: 'Toyota Racing',
    vehicleClass: 'JDM_TUNER',
    year: 1998,
    basePrice: 95000,
    marketValuation: 165000,
    engineType: 'INLINE_6',
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 326,
    torqueNm: 441,
    curbWeightKg: 1490,
    topSpeedKmh: 285,
    zeroToHundredSec: 4.6,
    brakingDistance100To0M: 34.0,
    lateralGForce: 1.05,
    fuelCapacityLiters: 70,
    paintColor: '#f97316',
    paintFinish: 'HIGH_GLOSS' as any,
    description: 'Legendary cast-iron block 2JZ-GTE capable of handling 1,200+ HP with single turbo conversions.',
  },
  {
    modelId: 'nissan_skyline_gtr_r34_vspec2',
    name: 'Nissan Skyline GT-R R34 V-Spec II RB26',
    brand: 'Nissan Motorsport',
    vehicleClass: 'JDM_TUNER',
    year: 2002,
    basePrice: 150000,
    marketValuation: 280000,
    engineType: 'INLINE_6',
    drivetrain: 'AWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 330,
    torqueNm: 392,
    curbWeightKg: 1540,
    topSpeedKmh: 280,
    zeroToHundredSec: 4.8,
    brakingDistance100To0M: 33.5,
    lateralGForce: 1.15,
    fuelCapacityLiters: 65,
    paintColor: '#1d4ed8',
    paintFinish: 'METALLIC',
    description: 'Bayside Blue icon with ATTESA E-TS PRO AWD, Getrag 6-speed, and Multi-Function Display.',
  },
  {
    modelId: 'mazda_rx7_fd3s_spirit_r',
    name: 'Mazda RX-7 Spirit R Type-A Twin-Rotor',
    brand: 'Mazda Hiroshima',
    vehicleClass: 'JDM_TUNER',
    year: 2002,
    basePrice: 85000,
    marketValuation: 145000,
    engineType: 'INLINE_4' as any, // 13B-REW Rotary
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 280,
    torqueNm: 314,
    curbWeightKg: 1270,
    topSpeedKmh: 275,
    zeroToHundredSec: 5.0,
    brakingDistance100To0M: 32.0,
    lateralGForce: 1.25,
    fuelCapacityLiters: 76,
    paintColor: '#cbd5e1',
    paintFinish: 'METALLIC',
    description: '13B-REW twin-rotor sequential turbo with 50:50 perfect front-midship weight distribution.',
  },
  {
    modelId: 'honda_nsx_type_r_na2',
    name: 'Honda NSX-R NA2 VTEC Lightweight',
    brand: 'Honda Precision',
    vehicleClass: 'JDM_TUNER',
    year: 2002,
    basePrice: 180000,
    marketValuation: 350000,
    engineType: 'V6_TWINTURBO' as any, // C32B NA V6
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 290,
    torqueNm: 304,
    curbWeightKg: 1270,
    topSpeedKmh: 280,
    zeroToHundredSec: 4.5,
    brakingDistance100To0M: 31.0,
    lateralGForce: 1.30,
    fuelCapacityLiters: 70,
    paintColor: '#ffffff',
    paintFinish: 'GLOSS',
    description: 'Championship White all-aluminum monocoque chassis developed with Ayrton Senna at Suzuka.',
  },
  {
    modelId: 'mitsubishi_lancer_evo_9_mr',
    name: 'Mitsubishi Lancer Evolution IX MR FQ-360',
    brand: 'Mitsubishi Rally',
    vehicleClass: 'JDM_TUNER',
    year: 2006,
    basePrice: 55000,
    marketValuation: 85000,
    engineType: 'INLINE_4',
    drivetrain: 'AWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 366,
    torqueNm: 492,
    curbWeightKg: 1400,
    topSpeedKmh: 260,
    zeroToHundredSec: 3.9,
    brakingDistance100To0M: 33.0,
    lateralGForce: 1.20,
    fuelCapacityLiters: 55,
    paintColor: '#dc2626',
    paintFinish: 'GLOSS',
    description: '4G63 MIVEC turbocharged iron block with Super Active Yaw Control (S-AYC) and Bilstein dampers.',
  },
  {
    modelId: 'subaru_impreza_wrx_sti_22b',
    name: 'Subaru Impreza 22B STi Widebody',
    brand: 'Subaru Rallye',
    vehicleClass: 'JDM_TUNER',
    year: 1998,
    basePrice: 120000,
    marketValuation: 320000,
    engineType: 'BOXER_6' as any, // EJ22 Boxer 4
    drivetrain: 'AWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 280,
    torqueNm: 363,
    curbWeightKg: 1270,
    topSpeedKmh: 250,
    zeroToHundredSec: 4.7,
    brakingDistance100To0M: 33.0,
    lateralGForce: 1.18,
    fuelCapacityLiters: 60,
    paintColor: '#1e40af',
    paintFinish: 'METALLIC',
    description: 'WRC homologation special celebrating Colin McRae with flared arches and adjustable center diff.',
  },
  {
    modelId: 'nissan_silvia_s15_spec_r',
    name: 'Nissan Silvia S15 Spec-R Aero SR20',
    brand: 'Nissan Motorsport',
    vehicleClass: 'JDM_TUNER',
    year: 2002,
    basePrice: 42000,
    marketValuation: 68000,
    engineType: 'INLINE_4',
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 250,
    torqueNm: 275,
    curbWeightKg: 1240,
    topSpeedKmh: 245,
    zeroToHundredSec: 5.4,
    brakingDistance100To0M: 34.5,
    lateralGForce: 1.15,
    fuelCapacityLiters: 65,
    paintColor: '#ffffff',
    paintFinish: 'METALLIC',
    description: 'The ultimate Japanese drift chassis featuring ball-bearing T28 turbo SR20DET and helical LSD.',
  },
  {
    modelId: 'toyota_ae86_sprinter_trueno',
    name: 'Toyota Sprinter Trueno AE86 4A-GE Group-A',
    brand: 'Toyota Racing',
    vehicleClass: 'JDM_TUNER',
    year: 1986,
    basePrice: 28000,
    marketValuation: 65000,
    engineType: 'INLINE_4',
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 240,
    torqueNm: 210,
    curbWeightKg: 860,
    topSpeedKmh: 225,
    zeroToHundredSec: 5.6,
    brakingDistance100To0M: 32.0,
    lateralGForce: 1.35,
    fuelCapacityLiters: 50,
    paintColor: '#ffffff',
    paintFinish: 'GLOSS',
    description: 'Panda white Touge drift legend revving to 11,000 RPM with carbon hood and dry-sump 4A-GE.',
  },
  {
    modelId: 'nissan_350z_hr_track',
    name: 'Nissan Fairlady Z33 VQ35HR Formula Drift',
    brand: 'Nissan Motorsport',
    vehicleClass: 'JDM_TUNER',
    year: 2008,
    basePrice: 32000,
    marketValuation: 45000,
    engineType: 'V6_TWINTURBO' as any,
    drivetrain: 'RWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 313,
    torqueNm: 363,
    curbWeightKg: 1530,
    topSpeedKmh: 250,
    zeroToHundredSec: 5.1,
    brakingDistance100To0M: 34.0,
    lateralGForce: 1.10,
    fuelCapacityLiters: 80,
    paintColor: '#9333ea',
    paintFinish: 'METALLIC',
    description: 'High-revving dual-throttle intake VQ35HR with Wisefab angle kit for 70-degree drift steering lock.',
  },
  {
    modelId: 'toyota_gr_yaris_wrc_homologation',
    name: 'Toyota GR Yaris Morizo AWD Pocket Rocket',
    brand: 'Toyota Racing',
    vehicleClass: 'JDM_TUNER',
    year: 2024,
    basePrice: 48000,
    marketValuation: 58000,
    engineType: 'INLINE_4' as any, // G16E-GTS 3-Cyl
    drivetrain: 'AWD',
    transmissionType: 'MANUAL_6SPD',
    horsepower: 300,
    torqueNm: 400,
    curbWeightKg: 1280,
    topSpeedKmh: 230,
    zeroToHundredSec: 4.8,
    brakingDistance100To0M: 31.5,
    lateralGForce: 1.25,
    fuelCapacityLiters: 50,
    paintColor: '#ffffff',
    paintFinish: 'METALLIC',
    description: 'GR-FOUR AWD system with dual Torsen differentials and forged carbon roof panel.',
  },
];
