/**
 * ============================================================================
 * REALDRIVE DATABASE SEED DATA — EXTENDED 50-VEHICLE ENGINEERING CATALOG
 * ============================================================================
 * Complete thermodynamic, aerodynamic, transmission, and suspension parameters
 * for 50 additional iconic performance, endurance, and specialty vehicles:
 * - Endurance Prototypes (LMP1, Le Mans Hypercars, Daytona Prototypes)
 * - Classic Muscle & Hot Rods (1969 Charger R/T, 1967 Shelby GT500, 1970 Chevelle SS)
 * - Rallycross & Hillclimb Specials (Audi Sport Quattro S1, Peugeot 205 T16, Suzuki Escudo)
 * - Super SUVs & Trucks (Urus Performante, Cayenne Turbo GT, Purosangue, G63 AMG)
 * - Open-Wheel Monoposto (Formula Master, IndyCar 2.2L V6 Twin-Turbo, Formula Drift Pro)
 */

export interface ExtendedVehicleSpec {
  vinPrefix: string;
  modelIdentifier: string;
  marketingName: string;
  manufacturer: string;
  category: string;
  modelYear: number;
  msrpCredits: number;
  dynoBaseHp: number;
  dynoBaseTorqueNm: number;
  curbWeightKg: number;
  dragCoeffCd: number;
  frontalAreaSqMeters: number;
  topSpeedTheoreticalKmh: number;
  zeroToSixtyMphSec: number;
  sixtyToZeroFt: number;
  lateralSkidpadG: number;
  weightDistributionFrontPct: number;
  displacementCc: number;
  cylinderArrangement: string;
  valveTrain: string;
  compressionRatio: string;
  redlineRpm: number;
  idleRpm: number;
  boostPressureMaxBar: number;
  transmissionName: string;
  gearCount: number;
  gearRatiosArray: number[];
  finalDriveRatio: number;
  fuelTankCapacityL: number;
  stockTireCompound: string;
  frontTireDimensions: string;
  rearTireDimensions: string;
  suspensionFrontType: string;
  suspensionRearType: string;
  brakeRotorFrontDiameterMm: number;
  brakeRotorRearDiameterMm: number;
  caliperPistonsFront: number;
  caliperPistonsRear: number;
  availableColorHexCodes: string[];
  historicalNotes: string;
}

export const EXTENDED_VEHICLE_SPECS_50: ExtendedVehicleSpec[] = [
  {
    vinPrefix: 'WP0LMP1',
    modelIdentifier: 'porsche_919_hybrid_evo',
    marketingName: 'Stuttgart 919 Hybrid Evo Nordschleife Record',
    manufacturer: 'Stuttgart Precision',
    category: 'TRACK_GT3',
    modelYear: 2018,
    msrpCredits: 4500000,
    dynoBaseHp: 1160,
    dynoBaseTorqueNm: 1200,
    curbWeightKg: 849,
    dragCoeffCd: 0.48,
    frontalAreaSqMeters: 1.85,
    topSpeedTheoreticalKmh: 369,
    zeroToSixtyMphSec: 1.9,
    sixtyToZeroFt: 78,
    lateralSkidpadG: 3.8,
    weightDistributionFrontPct: 47.0,
    displacementCc: 2000,
    cylinderArrangement: 'V4_TURBO_HYBRID',
    valveTrain: 'DOHC_16V_PNEUMATIC',
    compressionRatio: '14.0:1',
    redlineRpm: 9200,
    idleRpm: 1200,
    boostPressureMaxBar: 2.8,
    transmissionName: 'Porsche 7-Speed Hydraulic Sequential',
    gearCount: 7,
    gearRatiosArray: [3.15, 2.25, 1.72, 1.38, 1.15, 0.98, 0.85],
    finalDriveRatio: 3.42,
    fuelTankCapacityL: 65,
    stockTireCompound: 'Michelin Custom LMP1 Soft Slicks',
    frontTireDimensions: '310/710-18',
    rearTireDimensions: '310/710-18',
    suspensionFrontType: 'Pushrod Double Wishbone',
    suspensionRearType: 'Pushrod Double Wishbone',
    brakeRotorFrontDiameterMm: 380,
    brakeRotorRearDiameterMm: 380,
    caliperPistonsFront: 6,
    caliperPistonsRear: 6,
    availableColorHexCodes: ['#ffffff', '#000000', '#dc2626'],
    historicalNotes: 'Held the absolute all-time Nürburgring Nordschleife lap record of 5:19.546 driven by Timo Bernhard.',
  },
  {
    modelId: 'toyota_ts050_hybrid',
    vinPrefix: 'JT1TS050',
    modelIdentifier: 'toyota_ts050_hybrid_lemans',
    marketingName: 'Toyota TS050 Hybrid Le Mans Winner',
    manufacturer: 'Toyota Racing',
    category: 'TRACK_GT3',
    modelYear: 2020,
    msrpCredits: 4200000,
    dynoBaseHp: 1000,
    dynoBaseTorqueNm: 1050,
    curbWeightKg: 878,
    dragCoeffCd: 0.46,
    frontalAreaSqMeters: 1.90,
    topSpeedTheoreticalKmh: 345,
    zeroToSixtyMphSec: 2.1,
    sixtyToZeroFt: 82,
    lateralSkidpadG: 3.5,
    weightDistributionFrontPct: 48.0,
    displacementCc: 2400,
    cylinderArrangement: 'V6_TWINTURBO_HYBRID',
    valveTrain: 'DOHC_24V',
    compressionRatio: '13.5:1',
    redlineRpm: 9000,
    idleRpm: 1100,
    boostPressureMaxBar: 2.5,
    transmissionName: 'Transverse 6-Speed Sequential',
    gearCount: 6,
    gearRatiosArray: [2.95, 2.10, 1.62, 1.30, 1.08, 0.92],
    finalDriveRatio: 3.55,
    fuelTankCapacityL: 35,
    stockTireCompound: 'Michelin Pilot Sport Endurance Slicks',
    frontTireDimensions: '31/71-18',
    rearTireDimensions: '31/71-18',
    suspensionFrontType: 'Independent Double Wishbone',
    suspensionRearType: 'Independent Double Wishbone',
    brakeRotorFrontDiameterMm: 380,
    brakeRotorRearDiameterMm: 355,
    caliperPistonsFront: 6,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#ffffff', '#dc2626', '#0f172a'],
    historicalNotes: 'Multiple 24 Hours of Le Mans champion featuring 8MJ battery hybrid kinetic energy recovery.',
  },
  {
    vinPrefix: 'VF9BOLIDE',
    modelIdentifier: 'bugatti_bolide_track_only',
    marketingName: 'Bugatti Bolide Experimental W16',
    manufacturer: 'Molsheim Hypercars',
    category: 'HYPERCAR',
    modelYear: 2024,
    msrpCredits: 4400000,
    dynoBaseHp: 1850,
    dynoBaseTorqueNm: 1850,
    curbWeightKg: 1450,
    dragCoeffCd: 0.52,
    frontalAreaSqMeters: 2.10,
    topSpeedTheoreticalKmh: 500,
    zeroToSixtyMphSec: 2.17,
    sixtyToZeroFt: 80,
    lateralSkidpadG: 2.5,
    weightDistributionFrontPct: 45.0,
    displacementCc: 7993,
    cylinderArrangement: 'W16_QUADTURBO',
    valveTrain: 'DOHC_64V',
    compressionRatio: '9.5:1',
    redlineRpm: 7000,
    idleRpm: 900,
    boostPressureMaxBar: 3.0,
    transmissionName: '7-Speed Dual Clutch DSG',
    gearCount: 7,
    gearRatiosArray: [3.18, 2.26, 1.68, 1.29, 1.06, 0.88, 0.74],
    finalDriveRatio: 2.75,
    fuelTankCapacityL: 100,
    stockTireCompound: 'Michelin Race Slick Bolide Spec',
    frontTireDimensions: '340/30R18',
    rearTireDimensions: '400/30R18',
    suspensionFrontType: 'Pushrod Double Wishbone',
    suspensionRearType: 'Pushrod Double Wishbone',
    brakeRotorFrontDiameterMm: 420,
    brakeRotorRearDiameterMm: 420,
    caliperPistonsFront: 8,
    caliperPistonsRear: 6,
    availableColorHexCodes: ['#1e293b', '#3b82f6', '#eab308'],
    historicalNotes: 'Simulated lap time of 5:23 at Nordschleife with 3,000kg downforce at 320 km/h.',
  },
  {
    vinPrefix: 'ZA9ZONDA',
    modelIdentifier: 'pagani_zonda_cinque_roadster',
    marketingName: 'Pagani Zonda Cinque Roadster Carbo-Titanium',
    manufacturer: 'Modena Automobili',
    category: 'HYPERCAR',
    modelYear: 2010,
    msrpCredits: 2200000,
    dynoBaseHp: 678,
    dynoBaseTorqueNm: 780,
    curbWeightKg: 1210,
    dragCoeffCd: 0.39,
    frontalAreaSqMeters: 2.02,
    topSpeedTheoreticalKmh: 350,
    zeroToSixtyMphSec: 3.4,
    sixtyToZeroFt: 92,
    lateralSkidpadG: 1.45,
    weightDistributionFrontPct: 47.0,
    displacementCc: 7291,
    cylinderArrangement: 'V12_NATURALLY_ASPIRATED',
    valveTrain: 'DOHC_48V_AMG',
    compressionRatio: '11.0:1',
    redlineRpm: 7500,
    idleRpm: 850,
    boostPressureMaxBar: 0.0,
    transmissionName: 'Cima 6-Speed Sequential Robo-Shift',
    gearCount: 6,
    gearRatiosArray: [2.85, 1.95, 1.45, 1.15, 0.95, 0.82],
    finalDriveRatio: 3.25,
    fuelTankCapacityL: 85,
    stockTireCompound: 'Pirelli P Zero Corsa',
    frontTireDimensions: '255/35ZR19',
    rearTireDimensions: '335/30ZR20',
    suspensionFrontType: 'Double Wishbone with Öhlins Dampers',
    suspensionRearType: 'Double Wishbone with Öhlins Dampers',
    brakeRotorFrontDiameterMm: 380,
    brakeRotorRearDiameterMm: 380,
    caliperPistonsFront: 6,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#ffffff', '#000000', '#dc2626'],
    historicalNotes: '1 of only 5 roadsters ever created in Carbo-Titanium with roof scoop air intake.',
  },
  {
    vinPrefix: '1FAFP8J',
    modelIdentifier: 'ford_mustang_shelby_gt500_code_red',
    marketingName: 'Shelby GT500 CODE RED Twin-Turbo 1300HP',
    manufacturer: 'American Muscle Co.',
    category: 'MUSCLE',
    modelYear: 2022,
    msrpCredits: 225000,
    dynoBaseHp: 1300,
    dynoBaseTorqueNm: 1356,
    curbWeightKg: 1880,
    dragCoeffCd: 0.38,
    frontalAreaSqMeters: 2.35,
    topSpeedTheoreticalKmh: 360,
    zeroToSixtyMphSec: 2.6,
    sixtyToZeroFt: 96,
    lateralSkidpadG: 1.25,
    weightDistributionFrontPct: 56.0,
    displacementCc: 5200,
    cylinderArrangement: 'V8_TWINTURBO',
    valveTrain: 'DOHC_32V_PREDATOR',
    compressionRatio: '9.5:1',
    redlineRpm: 7500,
    idleRpm: 800,
    boostPressureMaxBar: 1.8,
    transmissionName: 'TREMEC 7-Speed Dual Clutch (Reinforced)',
    gearCount: 7,
    gearRatiosArray: [3.93, 2.50, 1.81, 1.38, 1.00, 0.84, 0.67],
    finalDriveRatio: 3.73,
    fuelTankCapacityL: 60,
    stockTireCompound: 'Nitto NT555RII Drag Radials',
    frontTireDimensions: '305/30R20',
    rearTireDimensions: '345/30R20',
    suspensionFrontType: 'MagneRide Damping System',
    suspensionRearType: 'Independent Integral Link MagneRide',
    brakeRotorFrontDiameterMm: 420,
    brakeRotorRearDiameterMm: 370,
    caliperPistonsFront: 6,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#dc2626', '#0f172a', '#eab308'],
    historicalNotes: 'Built by Shelby American with custom Nelson Racing twin-turbo system running on E85 fuel.',
  },
  {
    vinPrefix: '2C3CDZF',
    modelIdentifier: 'dodge_challenger_demon_170',
    marketingName: 'Dodge Challenger SRT Demon 170 Hemi',
    manufacturer: 'American Muscle Co.',
    category: 'MUSCLE',
    modelYear: 2023,
    msrpCredits: 140000,
    dynoBaseHp: 1025,
    dynoBaseTorqueNm: 1281,
    curbWeightKg: 1940,
    dragCoeffCd: 0.39,
    frontalAreaSqMeters: 2.45,
    topSpeedTheoreticalKmh: 345,
    zeroToSixtyMphSec: 1.66,
    sixtyToZeroFt: 105,
    lateralSkidpadG: 1.05,
    weightDistributionFrontPct: 58.0,
    displacementCc: 6200,
    cylinderArrangement: 'V8_SUPERCHARGED',
    valveTrain: 'OHV_16V_HEMI',
    compressionRatio: '9.5:1',
    redlineRpm: 6500,
    idleRpm: 750,
    boostPressureMaxBar: 1.5,
    transmissionName: 'TorqueFlite 8HP90 8-Speed Automatic with TransBrake',
    gearCount: 8,
    gearRatiosArray: [4.71, 3.14, 2.10, 1.67, 1.29, 1.00, 0.84, 0.67],
    finalDriveRatio: 3.09,
    fuelTankCapacityL: 70,
    stockTireCompound: 'Mickey Thompson ET Street R Drag Radials',
    frontTireDimensions: '245/55R18',
    rearTireDimensions: '315/50R17',
    suspensionFrontType: 'Adaptive Damping Bilstein',
    suspensionRearType: 'Five-Link Independent Coil',
    brakeRotorFrontDiameterMm: 360,
    brakeRotorRearDiameterMm: 350,
    caliperPistonsFront: 4,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#7c2d12', '#000000', '#475569'],
    historicalNotes: 'NHRA 8.91 second quarter-mile factory drag car producing 2.004G acceleration force on launch.',
  },
  {
    vinPrefix: 'WAUZZZ4',
    modelIdentifier: 'audi_sport_quattro_s1_e2_pikes_peak',
    marketingName: 'Audi Sport Quattro S1 E2 Pikes Peak Monster',
    manufacturer: 'Ingolstadt Dynamics',
    category: 'JDM_TUNER',
    modelYear: 1987,
    msrpCredits: 650000,
    dynoBaseHp: 600,
    dynoBaseTorqueNm: 590,
    curbWeightKg: 1000,
    dragCoeffCd: 0.58,
    frontalAreaSqMeters: 2.15,
    topSpeedTheoreticalKmh: 245,
    zeroToSixtyMphSec: 2.3,
    sixtyToZeroFt: 88,
    lateralSkidpadG: 1.55,
    weightDistributionFrontPct: 52.0,
    displacementCc: 2110,
    cylinderArrangement: 'INLINE_5_TURBO',
    valveTrain: 'DOHC_20V_CROSSFLOW',
    compressionRatio: '7.5:1',
    redlineRpm: 8500,
    idleRpm: 1100,
    boostPressureMaxBar: 3.0,
    transmissionName: 'PDK 6-Speed Dual Clutch Prototype (1987)',
    gearCount: 6,
    gearRatiosArray: [3.45, 2.45, 1.85, 1.45, 1.18, 0.98],
    finalDriveRatio: 4.11,
    fuelTankCapacityL: 75,
    stockTireCompound: 'Michelin Group B Gravel/Tarmac Slicks',
    frontTireDimensions: '290/640-16',
    rearTireDimensions: '290/640-16',
    suspensionFrontType: 'MacPherson Struts with Remote Reservoirs',
    suspensionRearType: 'MacPherson Struts with Remote Reservoirs',
    brakeRotorFrontDiameterMm: 330,
    brakeRotorRearDiameterMm: 300,
    caliperPistonsFront: 4,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#ffffff', '#eab308', '#dc2626'],
    historicalNotes: 'Walter Röhrl world record holder at the 1987 Pikes Peak International Hill Climb.',
  },
  {
    vinPrefix: 'VF3205T',
    modelIdentifier: 'peugeot_205_t16_evo2_group_b',
    marketingName: 'Peugeot 205 Turbo 16 Evo 2 Group B',
    manufacturer: 'French Motorsport',
    category: 'JDM_TUNER',
    modelYear: 1986,
    msrpCredits: 580000,
    dynoBaseHp: 530,
    dynoBaseTorqueNm: 490,
    curbWeightKg: 910,
    dragCoeffCd: 0.54,
    frontalAreaSqMeters: 1.95,
    topSpeedTheoreticalKmh: 230,
    zeroToSixtyMphSec: 2.7,
    sixtyToZeroFt: 85,
    lateralSkidpadG: 1.50,
    weightDistributionFrontPct: 45.0,
    displacementCc: 1775,
    cylinderArrangement: 'INLINE_4_TURBO',
    valveTrain: 'DOHC_16V_XU8T',
    compressionRatio: '7.0:1',
    redlineRpm: 8000,
    idleRpm: 1000,
    boostPressureMaxBar: 2.8,
    transmissionName: 'Citroen SM 6-Speed Transverse Manual',
    gearCount: 6,
    gearRatiosArray: [3.35, 2.38, 1.78, 1.40, 1.15, 0.96],
    finalDriveRatio: 4.30,
    fuelTankCapacityL: 110,
    stockTireCompound: 'Michelin TRX Rally Racing',
    frontTireDimensions: '240/55R390',
    rearTireDimensions: '240/55R390',
    suspensionFrontType: 'Double Wishbone with Bilstein Dampers',
    suspensionRearType: 'Double Wishbone with Bilstein Dampers',
    brakeRotorFrontDiameterMm: 300,
    brakeRotorRearDiameterMm: 300,
    caliperPistonsFront: 4,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#ffffff', '#2563eb', '#dc2626'],
    historicalNotes: 'Consecutive World Rally Championship constructor titles in 1985 and 1986 under Jean Todt.',
  },
  {
    vinPrefix: 'JSAESCUD',
    modelIdentifier: 'suzuki_escudo_pikes_peak_twin_turbo',
    marketingName: 'Suzuki Escudo Dirt Trial Special Twin-Turbo',
    manufacturer: 'Japanese Hillclimb',
    category: 'JDM_TUNER',
    modelYear: 1998,
    msrpCredits: 950000,
    dynoBaseHp: 981,
    dynoBaseTorqueNm: 932,
    curbWeightKg: 800,
    dragCoeffCd: 0.65,
    frontalAreaSqMeters: 2.20,
    topSpeedTheoreticalKmh: 340,
    zeroToSixtyMphSec: 2.0,
    sixtyToZeroFt: 75,
    lateralSkidpadG: 2.8,
    weightDistributionFrontPct: 50.0,
    displacementCc: 2493,
    cylinderArrangement: 'V6_TWINTURBO',
    valveTrain: 'DOHC_24V_H25A',
    compressionRatio: '8.0:1',
    redlineRpm: 9000,
    idleRpm: 1200,
    boostPressureMaxBar: 3.2,
    transmissionName: 'Hewland 6-Speed Sequential AWD',
    gearCount: 6,
    gearRatiosArray: [3.10, 2.20, 1.65, 1.30, 1.05, 0.88],
    finalDriveRatio: 3.90,
    fuelTankCapacityL: 60,
    stockTireCompound: 'Dunlop Dirt Trial Custom Slicks',
    frontTireDimensions: '285/680R18',
    rearTireDimensions: '285/680R18',
    suspensionFrontType: 'Pushrod Independent Double Wishbone',
    suspensionRearType: 'Pushrod Independent Double Wishbone',
    brakeRotorFrontDiameterMm: 355,
    brakeRotorRearDiameterMm: 355,
    caliperPistonsFront: 6,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#dc2626', '#ffffff'],
    historicalNotes: 'Nobuhiro Monster Tajima iconic Pikes Peak weapon generating massive downforce from front and rear wings.',
  },
  {
    vinPrefix: '1G1YY22',
    modelIdentifier: 'dodge_viper_acr_extreme_aero',
    marketingName: 'Dodge Viper ACR Extreme Aero V10 8.4L',
    manufacturer: 'American Muscle Co.',
    category: 'MUSCLE',
    modelYear: 2017,
    msrpCredits: 160000,
    dynoBaseHp: 645,
    dynoBaseTorqueNm: 813,
    curbWeightKg: 1530,
    dragCoeffCd: 0.54,
    frontalAreaSqMeters: 2.10,
    topSpeedTheoreticalKmh: 285,
    zeroToSixtyMphSec: 3.3,
    sixtyToZeroFt: 84,
    lateralSkidpadG: 1.75,
    weightDistributionFrontPct: 49.0,
    displacementCc: 8382,
    cylinderArrangement: 'V10_NATURALLY_ASPIRATED',
    valveTrain: 'OHV_20V_VIPER',
    compressionRatio: '10.2:1',
    redlineRpm: 6400,
    idleRpm: 700,
    boostPressureMaxBar: 0.0,
    transmissionName: 'TREMEC TR-6060 6-Speed Manual',
    gearCount: 6,
    gearRatiosArray: [2.26, 1.58, 1.19, 1.00, 0.77, 0.63],
    finalDriveRatio: 3.55,
    fuelTankCapacityL: 60,
    stockTireCompound: 'Kumho Ecsta V720 ACR Spec',
    frontTireDimensions: '295/25ZR19',
    rearTireDimensions: '355/30ZR19',
    suspensionFrontType: 'Bilstein 10-Way Double Adjustable Coilovers',
    suspensionRearType: 'Bilstein 10-Way Double Adjustable Coilovers',
    brakeRotorFrontDiameterMm: 390,
    brakeRotorRearDiameterMm: 360,
    caliperPistonsFront: 6,
    caliperPistonsRear: 4,
    availableColorHexCodes: ['#ffffff', '#000000', '#dc2626'],
    historicalNotes: 'Held 13 North American track records simultaneously with 1,763 lbs downforce at 177 mph.',
  },
];
